### ISSUE TITLE
Leave Freenode for another network or chat platform

### ISSUE THREAD

**Issue by antony-jr** [AppImage/AppImageKit#1136] opened 2021-05-19 14:20 UTC
Freenode is now bought by Andrew Lee ~~who now plans to sell user data from Freenode so I strongly advice to move to Matrix or some other IRC network.~~

**Reference**: https://www.kline.sh/

**Comment by TheAssassin** [comment] 2021-05-19 16:02
> now bought by Andrew Lee

Wrong. They just bought that Ltd., but years ago. I would call it a "coup" or "hostile takeover" which is attempted now, though.

> plans to sell user data 

Haven't heard that yet. Source?

> move to Matrix or some other IRC network.

This is best discussed on IRC.

**Comment by antony-jr** [comment] 2021-05-19 16:42
I've worked with postmarketOS folks and Matrix seems like a very good option. I never regretted using Matrix, It's really good. Also it's a federated network.

**Comment by TheAssassin** [comment] 2021-05-19 17:23
>  The staff working at freenode said this, See https://www.kline.sh/ (But I can't confirm if it's real so I closed the issue.)

It does not say in a single word that that new ownership plans to sell user data. You probably misunderstand that topic. AFAICS, the issue is that one of the staffers sold some infra to that new guy. However, that doesn't mean _they_ will sell data. You should not just make bold wild claims like that.

**Comment by probonopd** [comment] 2021-05-22 10:51
On https://freenode.net/ Andrew Lee (rasengan) Chairman, freenode limited, shares his view. He claims to have been funding freenode since 2013 and it has been serving us very well. So unless there is _proof_ that freenode is doing something bad that affects us or our users negatively I'd say there is no need to change anything.

**Comment by TheAssassin** [comment] 2021-05-22 11:15
I have been reading in the situation, and your assessment is either very one-sided or way too superficial to be meaningful, @probonopd. You should read up on that topic properly.

There is plenty of evidence that Lee's statements are blunt lies or just so imprecise that they don't hold. There are over 20 Freenode staff resignations, and the statements published by some of them all say the same. Lee's is not a "view", it's an attempt to spin the entire story to make the staff look evil and them like the savior. However, none of this can be believed. The entire "I have invested millions" part is so laughable, I don't see how you could take that serious. Just because they claim so doesn't mean it's true.

The statements from this Lee person cannot be verified. The statements of the staff, however, _can_ be verified. 

Freenode, the network, has always run on machines sponsored by other entities (this Lee person has not sponsored a single one of those), and has been run by volunteers. This Freenode Ltd. entity was only ever created in order to manage these #live conferences, and has not funded the network. It was communicated to the staff and the users that this Ltd. would not interfere with the day-to-day operation. However, that was a lie from the ex head of staff, who apparently sold the entire network without any right to do so to benefit financially. The staff and the users have been told that none of this would affect the network. However, they secretly worked on this coup that is backed by lots of money and lawyers.

From the staff, nobody has ever been asking for that Lee person to show up, as far as I can see. Freenode Ltd. apparently should have no legal control over the network. To me, it is clear that christel abused her position for personal financial gain, to the disadvantage of the IRC network consisting not only of staff but also the users.

Lee's corporate infrastructure has apparently even intimidated members of staff legally, and has tons of resources at their disposal. The staff cannot fight this without risking financial ruin. Therefore, they founded a new network.

It is _very_ apparent that this new "management" has no good intentions. Using lawyers to intimidate people to grab for power clearly communicates that. They have intentionally ruined the biggest IRC network left for reasons we can only guess about. The only right thing to do is to stand behind the people who have been running the network for over 20 years and move to Libera.Chat. That new network has a *way* better governance model, is organized as a Swedish non-profit, and tries to continue what Freenode began and what was betrayed in 2017 with the founding and sale of Freenode Ltd.

Staying on Freenode is not only morally wrong, but communicates that AppImage finds Lee's coup acceptable, which I clearly do not support.

Tons of projects have moved already (some are in the process):

- Python software foundation
- Wikimedia
- cURL
- CentOS
- Ubuntu (official resolution: https://lists.ubuntu.com/archives/ubuntu-irc/2021-May/001922.html)
- FOSDEM
- many Apache Foundation projects
- Haskell
- Grafana
- IRCv3
- musl
- Clear Linux
- NewPipe
- ...

I could continue that list much further...

There is also plenty media coverage:

- https://www.heise.de/news/IRC-Netz-Freenode-ist-tot-es-lebe-Libera-Chat-6050724.html
- https://hackaday.com/2021/05/20/freenode-debacle-prompts-staff-exodus-new-network/
- https://gnulinux.ch/freenode-betreiber-gruenden-libera-chat
- https://www.theregister.com/2021/05/19/freenode_staff_resigns/
- ...

Statements from Freenode staffers:

- https://blog.bofh.it/debian/id_461 (my favorite)
- https://kline.sh/
- https://gist.github.com/aaronmdjones/1a9a93ded5b7d162c3f58bdd66b8f491
- https://gist.github.com/pinkisemils/39d4ded8b1639b6f39dcab15618649f5
- https://fuchsnet.ch/freenode-resign-letter.txt
- https://gist.github.com/jesopo/45a3e9cdbe517dc55e6058eb43b00ed9
- https://gist.github.com/JonathanD82/6518b93708e0aaf4b8f92c8e7200816d
- https://mniip.com/freenode.txt
- https://mniip.com/freenode.txt
- http://jeremiad.org/freenode.shtml
- https://swantzter.se/freenode-resignation/

**Comment by probonopd** [comment] 2021-05-22 11:37
Agree. Let's continue to monitor the situation. We should not blindly follow the claims of either side. Whatever may be have happened _inside_ the project/company is a different matter though and one I as an "outsider" am not even interested in; it's politics like can be found in many companies/organizations. What counts for us is what it means for _our users_.

**Comment by TheAssassin** [comment] 2021-05-22 11:53
> The statements from this Lee person cannot be verified. The statements of the staff, however, can be verified.

Could I get any _more_ clear?

> Agree. Let's continue to monitor the situation. We should not blindly follow the claims of either side.

You were following claims. I have invested a couple hours and can tell I believe the staff and can verify most of their statements.

> What counts for us is what it means for our users.

That's the point. We need to switch. The _users_ already _have_ switched, at least the ones who are not constantly idle (i.e., never online) or on Matrix (problem to be solved within a few days). Make it official, _now_, and use these days to inform everyone that we're moving. Period.

The channel already counts 10 people over on Libera, and still counting.

https://meta.wikimedia.org/wiki/IRC/Migrating_to_Libera_Chat

**Comment by probonopd** [comment] 2021-05-22 12:11
The point I was trying to make was simply: If Freenode does somehting nasty to the _users_, such as sell user data, then we should be moving _yesterday_.
If half of the people are now talking on Libera Chat and the other half on freenode, well, then the situation has worsened for our _users_, which in itself may be reason enough to switch completely, and leave a clear message on freenode where to find us.

**Comment by TheAssassin** [comment] 2021-05-22 12:14
> If Freenode does somehting nasty to the users

Everything so far has been nasty enough to make all other projects move, and thousands of users giving up their accounts there. I cannot yet because I still maintain communities, but except for AppImage, all are moving.

> such as sell user data

You cannot trust them. That should be enough. I don't really want to wait until they really start doing harm to user data.

> If half of the people are now talking on Libera Chat and the other half on freenode

The only good way is to make a clean cut. Sorry if that hasn't got clear yet. I plan to just move entirely, leaving some messages in place in order to redirect users.

**Comment by antony-jr** [comment] 2021-05-22 14:18
Sorry but I think I made a big mistake opening this issue. This is a lot of drama to handle :laughing: :rofl: :laughing: :rofl: :laughing: :rofl:

**Comment by probonopd** [comment] 2021-05-23 16:46
No worries @antony-jr - the whole freenode thing has a lot of drama but it is not your fault at all.

**Comment by probonopd** [comment] 2021-06-02 16:42
We still need to change it in a couple of places:
https://github.com/search?q=org%3AAppImage+freenode

**Comment by probonopd** [comment] 2021-06-02 17:02
Part of me wants to send @rasengan an invoice for all the extra hours this has caused. Setting up new bridges, changing all the code, changing all the documentation, etc. in this and in other projects.

**Comment by TheAssassin** [comment] 2021-06-02 17:03
For the record, `irc.freenode.net` was _never_ correct. It's been `chat.` (well, probably still is, but we don't care).

**Comment by TheAssassin** [comment] 2021-06-02 18:19
Closing as resolved.

**Comment by TheAssassin** [comment] 2021-06-02 18:20
By the way, @probono, you had the chance to just link to the contact page now. Would've been easier.

**Closed by TheAssassin** 2021-06-02 18:19 UTC

**Comment by Symbian9** [comment] 2021-10-01 22:41
Please, updated current repo description too:

![Screenshot_2021-10-01_21-47-29](https://user-images.githubusercontent.com/13188580/135693314-16c78e81-7428-45df-b82c-bcf7478c41ef.png)

**Comment by TheAssassin** [comment] 2021-10-02 02:25
Done.

**Comment by Tachi107** [comment] 2022-04-29 19:26
The image in the README still mentions irc.freenode.net

https://github.com/AppImage/AppImageKit/blob/e30750f54a0f73e39e7d7ce69e61ab7ab5e3609e/README.md?plain=1#L6

![appimagekitr](https://user-images.githubusercontent.com/2480569/34471155-5b53131a-ef41-11e7-90a0-8c57b3c21551.png)

**Comment by probonopd** [comment] 2022-04-29 19:32
Great catch @Tachi107. Gone!
