### ISSUE TITLE
Recursive mode for --appimage-extract <some_path>

### ISSUE THREAD

**Issue by estan** [AppImage/AppImageKit#370] opened 2017-03-20 10:23 UTC
Would be nice if there was a recursive mode (maybe it could even be the default?) when specifying a path to `--appimage-extract`. E.g.

    ./orexplore-insight-0.5.2-17-gbd04fbf-x86_64.AppImage --appimage-extract "usr/share/icons/*"
    squashfs-root/usr/share/icons/hicolor

But I have a bunch of files under `usr/share/icons/*` there that I wanted to extract.

**Comment by estan** [comment] 2017-03-20 10:31
As a side note: If not specifying a path (using `--appimage-extract`) then the full content is extracted recursively.

**Comment by probonopd** [comment] 2017-03-20 19:12
Duplicate of https://github.com/probonopd/AppImageKit/issues/363?

**Comment by estan** [comment] 2017-03-20 21:11
@probonopd: Hm, I saw that bug, but that's not about recursive mode, or is it? What that bug description says is already possible (extracting individual files), and https://github.com/probonopd/AppImageKit/issues/363#issuecomment-282591250 seems to just be about a bug that it's not creating intermediate directories when extracting single files (giving fopen errors).

But you're right, maybe both these things should be fixed in one go, and a single issue enough.

**Comment by estan** [comment] 2017-03-20 21:14
Tell me if you want me to close this, and then we could update the description of #363 to note that it should work recursively if the path is a directory.

I might have time to make a PR, but not right now as I'm too swamped at work :/

**Comment by probonopd** [comment] 2017-03-20 22:19
Not sure I understand what you mean with "recursively" here, but wildcards should be supported as far as I remember.

**Comment by estan** [comment] 2017-03-21 08:26
With recursive, I mean that if I do `--appimage-extract <some_path>`, where `<some_path>` refers to a directory inside the image, then `<some_path>` including its contents should (recursively) be extracted.

At the moment, only the directory itself is extracted, even if it has other files/directories in it. E.g:

```
estan@newton:~$ ./orexplore-insight-0.5.2-17-gbd04fbf-x86_64.AppImage --appimage-extract usr/bin
squashfs-root/usr/bin
estan@newton:~$ ls squashfs-root/usr/bin/
totalt 0
estan@newton:~$
```

And even with wildcards, the behavior is not recursive. Say I wanted to extract all of `usr/share/icons`:

```
estan@newton:~$ ./orexplore-insight-0.5.2-17-gbd04fbf-x86_64.AppImage --appimage-extract "usr/share/icons/*"
squashfs-root/usr/share/icons/hicolor
estan@newton:~$
estan@newton:~$ ls squashfs-root/usr/share/icons/hicolor/
totalt 0
estan@newton:~$
```

The wildcard worked, all content in `usr/share/icons` was extracted, but it was not recursive, so all I got was the `hicolor` directory, not it's content.

**Comment by estan** [comment] 2017-03-21 08:30
And just to clarify my examples above, I do have things in `usr/bin` and `usr/share/icons`. For example:

```
estan@newton:~$ mkdir -p squashfs-root/usr/bin
estan@newton:~$ ./orexplore-insight-0.5.2-17-gbd04fbf-x86_64.AppImage --appimage-extract "usr/bin/orexplore-insight"
squashfs-root/usr/bin/orexplore-insight
estan@newton:~$ ls -l squashfs-root/usr/bin/orexplore-insight 
-rwxr-xr-x 1 estan estan 16392 mar 21 09:29 squashfs-root/usr/bin/orexplore-insight
estan@newton:~$
```

```
estan@newton:~$ mkdir -p squashfs-root/usr/share/icons/hicolor/32x32/apps
estan@newton:~$ ./orexplore-insight-0.5.2-17-gbd04fbf-x86_64.AppImage --appimage-extract "usr/share/icons/hicolor/32x32/apps/orexplore-insight.png"
squashfs-root/usr/share/icons/hicolor/32x32/apps/orexplore-insight.png
estan@newton:~$ ls -l squashfs-root/usr/share/icons/hicolor/32x32/apps/orexplore-insight.png
-rw-r--r-- 1 estan estan 996 mar 21 09:28 squashfs-root/usr/share/icons/hicolor/32x32/apps/orexplore-insight.png
estan@newton:~$
```

**Comment by probonopd** [comment] 2017-03-21 16:43
Ah, now I understand you. We would probably need to "traverse the tree" for this. PRs welcome.

**Closed** 2019-01-10 01:02 UTC
