### ISSUE TITLE
Current working directory and passing relative paths as arguments

### ISSUE THREAD

**Issue by FreeSlave** [AppImage/AppImageKit#479] opened 2017-09-16 19:49 UTC
For my app I took default AppRun and used appimagetool to create AppImage file.
The problem is that I can't pass relative path arguments as before because for some reason application does not inherit current working directory of the shell and sets it to somewhere in the mounted image.
Who is responsible? The way how appimage is packaged or AppRun?
How to fix this problem? Should I design my own AppRun?
Why is this behavior default? That's very unexpected since it breaks things (i.e. usual working flow with the app)

**Comment by TheAssassin** [comment] 2017-09-16 20:00
@FreeSlave it's not `AppRun`. Since you mention it: do you still use the tools from https://github.com/AppImage/AppImages? You should switch to https://github.com/probonopd/linuxdeployqt, which doesn't install such a script any more but properly configures paths inside the executable and its libraries.

The problem is the workaround in the runtime @probonopd added to make binpatching work. I already explained it on GitHub: To allow apps which hardcode paths like `/usr/some/.../thing`, those binaries are patched by replacing `/usr` to `././`, thus making those parts relative. Unfortunately, this makes it mandatory for the AppImage runtime (which is inserted into the AppImage by appimagetool) to `chdir()` to `usr/` inside the AppDir mount.

By deprecating the binary patching (which we planned anyway) we wouldn't have to fiddle with the current working directory any more. What do you think, @probonopd?

**Comment by FreeSlave** [comment] 2017-09-16 20:04
@TheAssassin, I used binaries from here https://github.com/AppImage/AppImageKit/releases/tag/continuous
I did not do any binary patching myself and not sure if I even need one in my case.

**Comment by probonopd** [comment] 2017-09-16 20:42
> @FreeSlave it's not AppRun

Yes it is: https://github.com/AppImage/AppImageKit/blob/39a5b616ce0f82c549e696c31f43375a7bdc703d/AppRun.c#L151

> Should I design my own AppRun?

Yes, that would be an option. E.g., `linuxdeployqt` even uses just a symlink to the main executable instead of an `AppRun` script or binary.

**Comment by azubieta** [comment] 2018-11-24 00:07
Closing due inactivity. Please reopen if required.

**Comment by probonopd** [comment] 2018-11-24 10:42
We could consider to check for the presence of some metadata in the AppDir (e.g., `X-AppImage-PayloadIsRelocateable=true` -- need to think about a better name) and if that is present, skip the `chdir()`. 

What do you think?

**Comment by TheAssassin** [comment] 2018-11-24 11:11
The runtime doesn''t perform any `chdir`. It's ye olde AppRun code, which we don't like anyway because of exactly such things.

The desktop file isn't really the place for such data, but it's being read by AppRun anyway, so that sounds like a viable option. However, virtually _any_ AppImage that is using AppRun would have to set this to false, if built using that old script code (which we _really_ have to get rid of!).

IMO we can close this, as noone else has ever asked for this again. People use tools like linuxdeploy to _eliminate_ the need for `AppRun.c`.

**Comment by probonopd** [comment] 2018-11-24 11:14
> The runtime doesn''t perform any chdir. It's ye olde AppRun code

Correct, I had confused it, sorry.

> However, virtually any AppImage that is using AppRun would have to set this to false

Well, changes that change the functionality should always be opt-in such as not to break everything existing that is relying on the current functionality.

**Comment by TheAssassin** [comment] 2018-11-24 14:09
AppRun doesn't even have a proper desktop file parser, and I think we shouldn't implement any more features there but push forward to using relocatable binaries.

I'd close this issue, and reopen on future requests. We shouldn't invest any time for year-old issues if noone ever asked for this again.

**Closed by TheAssassin** 2018-11-24 14:09 UTC
