### ISSUE TITLE
Appimage Install/Uninstall Usability 

### ISSUE THREAD

**Issue by ianp5a** [AppImage/AppImageKit#769] opened 2018-05-04 10:39 UTC
Looking at new or non-IT users of Linux, installing software from a software centre or .deb file download requires no IT or command line knowledge, or even any need for detailed instructions.
Currently an appimage has some usability issues that are likely to become showstoppers for non IT users.
Downloading and making executable are NOT a problem. As both in the user realm. And well documented.
- **a)** On Linux, users have no indication of where to store programs. It will get left in the download folder or moved to somewhere that will get forgotten. Such a location is not documented. Or be deleted accidentally in a clean up
- **b)** There is no user friendly way to see currently installed appimages. Or to be able to uninstall* them.
*_Uninstall_ means removing any launcher icon created, the file itself and any setting folder it created. This becomes junk that needs cleaning out.

**Request:** To make appimage use as seamless as other install methods. Where a and b (above) are solved. 
**Suggestion:** Something (like appimaged perhaps) is adapted to solve these problems. Where installation and use never requires the command line. E.G. "first run" could copy the appimage file to a "safe" location, and prompt download of appimaged. (In addition to creating the launcher icon).

See discussion here:
https://discourse.appimage.org/t/usability-problems-with-appimages/340

**Comment by TheAssassin** [comment] 2018-05-04 11:37
Check out [AppImageLauncher](https://github.com/TheAssassin/AppImageLauncher). It doesn't depend on appimaged, but provides a simple to use helper tool that takes care of running and integrating AppImages.

**Comment by ianp5a** [comment] 2018-05-04 11:46
Thanks. AppImageLauncher appears to cover _all_ the above requests. And looks good.
Regarding integration, is it intended for creators to add it to appimages for distribution? Or is it to install on the user side? I'm concerned about whether AppImageLauncher will be available to everyone when they find an appimage to download.

**Comment by azubieta** [comment] 2018-05-04 17:03
I would also add, to the discussion that there is an alternative to AppImageLauncher that don't require specific distributions packages. I must also say, to be fair, that it doesn't work when the AppImage is being opened from a CLI.
But in my opinion, if an user is capable of opening a terminal, it's also capable of running `chmod +x`.
  
https://github.com/nomad-desktop/appimage-desktop-integration

**Comment by TheAssassin** [comment] 2018-05-04 18:38
@azubieta your app does still require installation, same goes for mine, there is no difference in that. Please don't make false statements.

**Comment by azubieta** [comment] 2018-05-04 18:49
@TheAssassin I never said: "it doesn't require installation", i said "don't require specific distributions packages" because it is an AppImage. Please don't make false accusations.
Peace

**Comment by TheAssassin** [comment] 2018-05-04 18:54
@azubieta so, your app installs in the userspace? The OP requested distro packaging, actually, native packages are nothing bad. Also, they allow for cleaning up the files properly, and they have this nice feature called "install hooks".

**Comment by probonopd** [comment] 2018-05-04 21:51
Thank you for your thoughts @ianp5a. We are always interested in the first impression AppImage makes to new users.

Our ideal target scenario is that AppImages work as seamlessly as applications on the Mac, where no installation is needed. One can just download an application and use it, without installing desktop files, files for MIME types, etc. Unfortunately Linux desktops (currently!) don't work that way.

> Looking at new or non-IT users of Linux, installing software from a software centre or .deb file download requires no IT or command line knowledge, or even any need for detailed instructions.

Well, they need an administrator (root) password to begin with. Which we think is bad, because not all users have root rights on their machines (e.g., company employees or university computer lab users).

> Currently an appimage has some usability issues that are likely to become showstoppers for non IT users.
Downloading and making executable are NOT a problem. As both in the user realm. And well documented.

This is already all that is needed to successfully run the application. Everything else is purely optional and cosmetic. To be quite frank, for me personally, this is all that is needed.

> a) On Linux, users have no indication of where to store programs.

Which is by design. You can store (and run) applications from _any place you like_, including network shares, USB drives, and CD-ROMs. That's a great advantage of the AppImage format, just like with apps on the Mac. This is unlike Windows and traditional Linux, where you are supposed to install applications into fixed locations before you can use them. It's a feature, not a bug!

b) There is no user friendly way to see currently installed appimages. Or to be able to uninstall* them.

Because there is really nothing to "install". As for optional desktop integration using desktop files and whatnot, whatever solution (e.g., the optional `appimaged` daemon) that registers an AppImage with the system is also supposed to unregister it again when the AppImage is deleted.

> *Uninstall means removing any launcher icon created, the file itself and any setting folder it created. This becomes junk that needs cleaning out.

There is no "uninstall". You can delete the application (by deleting the AppImage file), but that will not (and should not) delete any documents (including settings files) created by that application. If you want to delete those, you need to use the file manager. This is by the way also true if you install applications the traditional way using a package manager. Uninstalling them using the package manager will not delete documents (including settings files in the home directory) either.

> Request: To make appimage use as seamless as other install methods. Where a and b (above) are solved.

We don't want AppImages to have a need to be "installed". We want them to be _easier_ than that.

> Suggestion: Something (like appimaged perhaps) is adapted to solve these problems. Where installation and use never requires the command line. E.G. "first run" could copy the appimage file to a "safe" location, and prompt download of appimaged. (In addition to creating the launcher icon).

The optional `appimaged` daemon does not require you to move anything anywhere. If you download an AppImage and appimaged is running, then it will automatically integrate the AppImage into the system (menus, MIME types, icons etc.) and will remove the integration once you delete the AppImage. No command line involved. You can leave the AppImages in the default Downloads directory, or can put them into any of the directories watched by `appimaged`. Ideally, it would watch the _whole system_, but unfortunately we haven't found a good way yet to make that happen (to equal the user experience on the Mac).

**Comment by ianp5a** [comment] 2018-05-08 10:38
Thanks for taking the time to go into detail

>Well, they need an administrator (root) password to begin with. Which we think is bad, because not all  users have root rights on their machines (e.g., company employees or university computer lab users).

I agree. And in many cases, like home users, root is nonsense just to install software. 

>This is already all that is needed to successfully run the application. Everything else is purely optional and cosmetic. To be quite frank, for me personally, this is all that is needed.

Optional maybe, but far from satisfactory. Doing nothing more, means the file gets left in the default Download folder, where it could too be easily cleaned out. There is a risk of losing the app. People don't want the risk, or junk building up.  If they move it right away, they need to know to where. I don't want to mix it in with my documents. And will I remember that location for the next appimage? 
I use Etcher. But I don't remember where I put the appimage file. Or, when I added the next one, that that I'd already got an appimage program. 
Also, if the file is moved _after_ first use, the launcher icon will fail to find the file. 

Yes it would great to have **appimaged** or similar, easy to discover and install. But you then rely on software distributors to mention it on their download page. Or get many distros to include it.  Maybe some auto install option could be possible.

**Comment by TheAssassin** [comment] 2018-05-08 17:11
@ianp5a well it's a trade-off with AppImageLauncher. You install something _once_ and then can enjoy first class AppImage support on your distro. In my opinion, and a lot of others agree, this is an acceptable effort to make. Some distros are soon going to ship AppImageLauncher upstream, so the installation step can be omitted.
I am going to present this on a conference soon, and hopefully, distros will change their mind, and offer some native support.

Soon we're hopefully going to offer native package repositories to provide users with updates with little effort. See https://github.com/TheAssassin/AppImageLauncher/issues/21.

**Comment by ianp5a** [comment] 2018-05-09 07:06
@TheAssassin  Great. Anything that reduces the divide between techies and normal users is good.  
As certain usability aspects of Appimage use add to the nerdy reputation of Linux.

**Comment by TheAssassin** [comment] 2018-05-09 09:59
> I use Etcher. But I don't remember where I put the appimage file. Or, when I added the next one, that that I'd already got an appimage program. As there is no overview of them.
Also, if the file is moved after first use, the launcher icon will fail to find the file.

Don't know if you saw that, but AppImageLauncher fixes all these points, and it has a simple-to-use uninstallation ability. It fixes the "all files scattered across entire system" thing as well. The problem with appimaged is that it's primarily built for @probonopd's "way of digital life". He doesn't use an installed OS like we do, but uses live images, meaning that the data will go away on reboot. This whole "an AppImage could remain in a spot I don't find it in" or "my Downloads directory is so large I can't find specific files in it" problem is nothing he's affected by.

As AppImage is an open project published free software, it's easy to develop alternatives, though.

**Comment by ianp5a** [comment] 2018-05-09 10:26
I'll certainly try.

**Comment by azubieta** [comment] 2018-11-27 02:51
This issue seems fulfilled. Closing it, please reopen if required.

**Closed by azubieta** 2018-11-27 02:51 UTC

**Comment by foxy49** [comment] 2018-12-27 14:38
Open Shot's AppImage file must save the previous user settings somewhere as having had freeze issues and then the program failing to launch and then endlessly loop looking for missing project files (it won't load when they are present),  I am at a loss how to fully uninstall.  I downloaded the latest version of the program (daily updates) and it still has all the same problems due to something going wrong with my source files,  just simple jpg files.

Anyone know where to look for the config files which clearly have been written somewhere on the system, as I just want to start a new project and forget the one that froze up and now is stuck in a permanent loop.

**Comment by probonopd** [comment] 2018-12-27 14:42
Please report the issue to the OpenShot team at https://github.com/OpenShot/openshot-qt/issues

**Comment by KurtPfeifle** [comment] 2018-12-27 22:14
>> a) On Linux, users have no indication of where to store programs.
>
> Which is by design. You can store (and run) applications from any place you like, including
> network shares, USB drives, and CD-ROMs. That's a great advantage of the AppImage
> format, just like with apps on the Mac. 

While this, formally speaking, is of course true.... in real life, a lot of Mac applications come as a *.pkg file.    
Which acts as an "installer".     
One that "installs" the .app bundle.     
One that defaults to place that .app bundle into either `/Applications` or `${HOME}/Applications`.
(While of course still leaving a user the liberty to put it anywhere else she likes.)

Maybe AppImage could copy a page from Mac's playbook and *recommend* for users to create */AppImages* and/or *${HOME}/AppImages* directories and store all AppImages there. (Such a recommendation does not take away the liberty of users to do otherwise...)

**Comment by probonopd** [comment] 2018-12-27 22:18
Yes, I never understood why Apple allowed `.pkg` installers in addition to their great app bundle format. I guess it is meant for more complex software that integrates deeper into the system than is possible with a mere `.app` (e.g., if a kernel extension a.k.a. `.kext` needs to be installed).

We do recommend `/Applications` (for system-wide AppImages), `mountpoint/Applications` (for AppImages on removable and/or additional drives), and `$HOME/Applications` (for per-user AppImages).

**Comment by KurtPfeifle** [comment] 2018-12-27 22:44
> Yes, I never understood why Apple allowed .pkg installers in addition to their great app bundle format. 

They allowed it to make it easier for those type of users who migrated from other systems which use installers. That included *vendors* who ported their software to macOS. Apple thought they shouldn't require this type of users to make their own decision about where to store the .app bundles. It boils down to add a bit more user-friendliness for new users....

> We do recommend /Applications (for system-wide AppImages), <mountpoint>/Applications (for AppImages on removable and/or additional drives), and $HOME/Applications (for per-user AppImages).

This recommendation isn't very prominent or very visible then. It isn't "hammered home" at many opportunities to do so.... *(says someone who hasn't followed AppImage development details for almost a year... 😜)*
