### ISSUE TITLE
fopen error when trying to --appimage-extract

### ISSUE THREAD

**Issue by probonopd** [AppImage/AppImageKit#457] opened 2017-08-28 16:35 UTC
```
me@host:~$ /home/me/Downloads/prusacontrol_0.9.2.297_beta.AppImage --appimage-extract                                                   
squashfs-root/.DirIcon
squashfs-root/AppRun
(...)
squashfs-root/PrusaControl-master/tools/Slic3r-Lite/bin/lib/site_perl
squashfs-root/PrusaControl-master/tools/Slic3r-Lite/bin/lib/site_perl/5.22.0
squashfs-root/PrusaControl-master/tools/Slic3r-Lite/bin/lib/site_perl/5.22.0/B.pm
fopen error
```
Need to investigate. First, can this be reproduced with the latest version of AppImageKit?

**Comment by probonopd** [comment] 2017-08-28 17:22
Sometimes the error only happens on the 2nd run. Without deleting the old `squashfs-root`. Possibly something to do with symlinks?

**Comment by azubieta** [comment] 2018-11-23 23:44
Unable to reproduce the issue. Closing it. Please reopen if something comes up.

**Closed by azubieta** 2018-11-23 23:44 UTC

**Comment by TheAssassin** [comment] 2018-11-23 23:47
@azubieta I guess it depends on the AppImage that is used. But you're right, we haven't seen any issues like that in more than a year.
