### ISSUE TITLE
Segfaults for latest `appimaged` and `appimagetool` builds

### ISSUE THREAD

**Issue by KurtPfeifle** [AppImage/AppImageKit#674] opened 2018-02-27 03:23 UTC
Latest continuous builds of appimaged and appimagetool segfault:

````
$> aiktb --scriptrun selftests.sh
[....]

 ================================
    Running check_updateinfo:
 ================================
             appimaged :          AppImageUpdate :  gh-releases-zsync|AppImage|AppImageUpdate|continuous|AppImageUpdate-*x86_64.AppImage.zsync
     AppImageUpdate-Qt :  gh-releases-zsync|AppImage|AppImageUpdate|continuous|AppImageUpdate-Qt-*x86_64.AppImage.zsync
    appimageupdatetool :  gh-releases-zsync|AppImage|AppImageUpdate|continuous|appimageupdatetool-*x86_64.AppImage.zsync
          appimagetool :           linuxdeployqt :  gh-releases-zsync|probonopd|linuxdeployqt|continuous|linuxdeployqt*-x86_64.AppImage.zsync
                zsync2 :  gh-releases-zsync|AppImage|zsync2|continuous|zsync2-*x86_64.AppImage.zsync
            zsyncmake2 :  gh-releases-zsync|AppImage|zsync2|continuous|zsyncmake2-*x86_64.AppImage.zsync
   appimagekit-toolbox :  

$> aiktb --appimage-extract
[....]

$> cd squashfs-root/usr/bin

$>  for i in appimaged appimagetool  ; do ./$i --appimage-version ; done
Version: continuous-7-gf703696
Version: continuous-7-gf703696

$>  for i in appimaged appimagetool  ; do ./$i --version ; done
appimaged, continuous build (commit continuous-7-gf703696), build 1471 built on 2018-02-27 01:06:01 UTC
appimagetool, continuous build (commit continuous-7-gf703696), build 1471 built on 2018-02-27 01:06:01 UTC

$>  for i in appimaged appimagetool  ; do sha256sum ./$i  ; done
3e7b68188b3b0bdb908517e35a3cf5800c30b8c86eb04ddd0e57c8fc7e121a7a  ./appimaged
0da7aa96db5f914b634a74147b35caa94c225734fc04d2b1a4ed9f348cbfe057  ./appimagetool

$> ######### Finally....

$>  for i in appimaged appimagetool  ; do ./$i --appimage-updateinfo ; done
Segmentation fault
Segmentation fault
````

The problem is with *Version: continuous-7-gf703696* (common denominator for affected tools):

````
k$>  for i in appimaged appimagetool AppImageUpdate AppImageUpdate-Qt appimageupdatetool linuxdeployqt zsync2 zsyncmake2 ; do ./$i --appimage-version ; done
Version: continuous-7-gf703696
Version: continuous-7-gf703696
Version: continuous-3-g1798afe
Version: continuous-3-g1798afe
Version: continuous-3-g1798afe
Version: continuous-4-g06f10fa
Version: continuous-2-g09dfd37
Version: continuous-2-g09dfd37
````

**Comment by probonopd** [comment] 2018-02-27 19:50
Thanks @KurtPfeifle for reporting this and for identifying this issue as the root cause for the "mysterious" AppImageHub failures we were encountering lately. @TheAssassin please have a look into this with high priority. Thank you.

**Comment by azubieta** [comment] 2018-03-01 20:53
Lot's of them :cry:
Here [one]( https://transfer.sh/kUbZL/githubdesktop-linux-1.0.13_x86_64.AppImage
) Appimage that produces crashes on my system.

**Comment by TheAssassin** [comment] 2018-03-01 20:58
@azubieta @probonopd these segfaults have been fixed already. I added checks to make sure bugs like the ones here won't be merged unseen again in the future.

Please ask the projects to rebuild their AppImages.

**Closed** 2018-03-01 20:59 UTC
Labels: bug, high-priority

**Comment by probonopd** [comment] 2018-03-03 10:42
Thank you.
