### ISSUE TITLE
Please support FreeBSD

### ISSUE THREAD

**Issue by ykla** [AppImage/AppImageKit#895] opened 2018-12-19 03:13 UTC
FreeBSD is an important BSD computer operation system, please support it.

**Comment by salamanderrake** [comment] 2018-12-19 05:30
If it runs on mac, it should by default run on FreeBSD.

**Comment by TheAssassin** [comment] 2018-12-19 22:59
Duplicate of #98. Please try the search next time, to avoid opening duplicate issues.

**Closed by TheAssassin** 2018-12-19 22:59 UTC
