### ISSUE TITLE
How to set icon for AppImage binary itself ??

### ISSUE THREAD

**Issue by keshavbhatt** [AppImage/AppImageKit#346] opened 2017-02-01 16:51 UTC
I created appimage of my two applications , both of them don't show thumbnail/icon for by their self
am i missing something ???
 
I also seen that filefox appimage also unable to show thumbnail/icon or itself while corebird appimage do.
![screenshot from 2017-02-01 22-19-46](https://cloud.githubusercontent.com/assets/5965031/22516749/cf492768-e8cc-11e6-9d5f-d1707863ad36.png)

**Comment by probonopd** [comment] 2017-02-05 21:31
This functionality was available as part of `runtime.c` for type 1 AppImages but it was a dirty hack not fully implementing the thumbnail spec and has been removed in favor of the optional `appimaged` daemon.

**Comment by chrisnharvey** [comment] 2017-02-15 15:30
Will this feature ever return? I personally recommend AppImages to people, for the primary reason that they can be downloaded and run without any additional tools (like appimaged). So if a user has a directory full of AppImages (like I do on several machines that do not run appimaged), then it is quite annoying for all of these apps to have the same icon.

**Comment by probonopd** [comment] 2017-02-15 22:15
It might come back if someone (= not me) implements the the whole full-blown [Thumbnail Managing Standard](https://specifications.freedesktop.org/thumbnail-spec/thumbnail-spec-latest.html)  in the AppImage runtime. Pull requests welcome.

**Comment by teras** [comment] 2017-11-27 21:35
Are you sure thumbnails are for files other than images?
I think nautilus uses the gio set metadata::custom-icon instead

**Comment by probonopd** [comment] 2017-11-27 21:38
@teras you are right. So if we can implement it "in the right way", even better! But let's keep in mind that this a) must not add heavy dependencies to `AppRun.c` (pure C) and must work on KDE, XFCE, Deepin, etc. too.

**Comment by teras** [comment] 2017-11-27 22:09
@probonopd I doesn't have any idea how it is on other desktop systems, and there could be millions of them :) Indeed the support should be global, but how?

**Comment by probonopd** [comment] 2017-11-27 22:37
The XDG Thumbnailer spec is implemented by every desktop. So as long as we use it we should be fine.

**Comment by azubieta** [comment] 2017-12-08 06:23
WIP at #578

**Comment by TheAssassin** [comment] 2017-12-21 00:14
The thumbnailer code has been merged. It just has to be implemented properly in the runtime. CC @probonopd

**Comment by probonopd** [comment] 2018-02-23 19:26
> It just has to be implemented properly in the runtime.

Do we still plan to do that? I think we should...

**Comment by TheAssassin** [comment] 2018-02-23 19:48
I don't think our plans on that have changed. We just need someone to do it.

**Comment by azubieta** [comment] 2018-11-23 04:55
Now we have a thumbnailers for gnome, kde and the default XDG thumbnails implementation. Therefore we can close the issue.

**Closed by azubieta** 2018-11-23 04:55 UTC
Labels: help-wanted, pr-welcome

**Comment by probonopd** [comment] 2018-11-23 04:56
@azubieta do we also have the feature that when no thumbnailer is installed, than merely running the app will put the thumbnail icon into the place specified by the XDG thumbnail spec?

**Comment by azubieta** [comment] 2018-11-23 05:10
The runtime is already linked to libappimage so it could be implemented. I just don't like the idea of adding more stuff to the runtime.

**Comment by probonopd** [comment] 2018-11-23 05:47
> The runtime is already linked to libappimage

I was not really aware of that... why have we done this?

> I just don't like the idea of adding more stuff to the runtime.

Agree, I am also a bit hesitant for the same reason. Also, it's a workaround rather than a proper solution in the sense of https://github.com/AppImage/appimaged/issues/30

**Comment by develar** [comment] 2018-11-23 07:12
@azubieta Ouch, it is incredible cool and useful, so, it is part of new runtime (sorry, do not see commit reference here)?

**Comment by probonopd** [comment] 2018-11-23 07:16
@develar please have a look at https://github.com/AppImage/appimaged/issues/30 - is this an area in which you would be interested enough to join a broader discussion and specification effort, e.g., on opendesktop.org? We want to get how applications can be integrated dynamically into the desktop "right" this time, and increasingly I think we cannot do it alone (as the AppImage project)

**Comment by TheAssassin** [comment] 2018-11-23 19:43
The runtime isn't linked to libappimage, but to one of it's modules that contains the functionality shared between libappimage (and anything that links to it) and AppImageKit (runtime, appimagetool etc.).
This was done due to the bad structure in the original source code, and it's by far the most elegant way to do it right now.

IIRC the XDG thumbnailing stuff is performed by the runtime on every startup already. That covers most desktop environments (among the big players, only KDE doesn't support that spec).

@azubieta would appreciate if you could look for the line in the code base where that thumbnailer is run. IIRC you implemented that ~ 1 year ago

**Comment by ChristianCiach** [comment] 2019-02-01 20:37
Today I stumbled upon this project and AppImages in general while investigating how we could deploy our app. After downloading some AppImages from the Hub, I noticed that some of them got an icon for their .AppImage-file after launching, but most did not.

As I understand it, this feature was removed from AppImageKit and people now need to a appimaged running to get this functionality. 

In my opinion, this is a huge step backwards. I think **the** main feature of AppImages is that they are completely standalone. Asking our users to install some daemon that is not even in the repos of any major linux distribution is a no-go. As I see it, there is not even a single tagged version of appimaged, just continuous builds (and the current one even crashes with a segmentation fault).

This sounded probably a lot harsher than I intended it to, and for this i apologize. I love the concept of AppImages and will probably deploy our software this way. It's just a bummer that the users have to deal with the default binary-file icon of their file browser, instead of a nice icon that is packaged with our AppImage (but that will never be seen by the users).

I sincerely hope that this feature will return without the need to force a daemon on our users!

**Comment by ChristianCiach** [comment] 2019-02-01 23:19
Quick and dirty workaround:

Assume your .desktop file launches a shellscript called start.sh:

```
[Desktop Entry]
Name=MyCoolApp
Exec=start.sh %F
```

Then you can put this into your start.sh:

#!/bin/bash

```
if [ ! -z "$APPIMAGE" ] && [ ! -z "$APPDIR" ]; then
    MD5=$(echo -n "file://$APPIMAGE" | md5sum | cut -d' ' -f1)
    cp "$APPDIR/usr/share/icons/hicolor/128x128/apps/mycoolapp.png" "$HOME/.cache/thumbnails/normal/$MD5.png"
    cp "$APPDIR/usr/share/icons/hicolor/256x256/apps/mycoolapp.png" "$HOME/.cache/thumbnails/large/$MD5.png"
    xdg-icon-resource forceupdate
fi

# Now start your actual app...
```

Adjust as necessary :) You do not need to provide files for multiple resolutions. We only provide a single 256x256 icon that I copy to "$HOME/.cache/thumbnails/large/" and it works just fine.

**Comment by ChristianCiach** [comment] 2019-02-01 23:30
> Indeed, we should have a GUI installer...

This surely would make things a lot easier! I do not know if appimaged updates itself, but i think this would also a requirement.

I really hope that appimaged or something like that will someday be part of every major linux distribution :)

**Comment by probonopd** [comment] 2019-02-01 23:32
Most traditional distributions are opposed to the AppImage concept because it means that users don't go the distribution for applications, only the base system.

**Comment by ChristianCiach** [comment] 2019-02-01 23:37
> It's basically why we removed it from `runtime.c`

Actually, this is exactly the code I learned from how to do this :) I didn't know about the XDG thumbnailing mechanics before.

Well, I will stop spamming now and will go to bed instead. I am happy with my improvised solution, even if it only works with GTK-based desktop environments. Maybe it helps someone. 

I am in the fortunate situation that my app will only be distributed inside our company, so I know that all users are using Gnome shell or XFCE. Of course, sometime in the future I will surely build such an app for the public, so I will keep my eyes on this issue :) Thank you for your hard work!

**Comment by yatima1460** [comment] 2019-05-22 00:41
@probonopd 

I understand almost nothing about this but what about looking at the problem from a different angle?

What if the AppImage when its run would spawn its own thumbnail in ~/.cache/thumbnails or something?

**Comment by mnesarco** [comment] 2020-12-27 03:23
Hi Friends,
As a workaround, I have created a linuxdeploy plugin to do the xdg thumbnail trick based on @ChristianCiach comment.

The plugin is a simple bash script: 
https://gist.github.com/mnesarco/6e5712ef836bfdd330178ff2bc9be54c

It adds a hook to generate the thumbnail.

Example usage:

```
export XDG_ICON=/path/to/my/png/icon
linuxdeploy --appdir=[...] -d [...] -i [...] --plugin xdg --output appimage

```

**Comment by probonopd** [comment] 2020-12-27 06:59
Thanks @mnesarco.

**Comment by mnesarco** [comment] 2020-12-27 13:28
Thanks @probonopd , yes you are absolutely right. The XDG Thumbnail Spec is so weird, so much that file managers ignore the metadata :D. I was looking desesperately to a solution to set the icon without resorting to installing any daemon. So I tested the @ChristianCiach solution and it worked only to show AppImage with the icon in the file manager, it does not work for example to show the icon on the dock when launched. So I have resorted to another approach:

Now I have created a script to transform the AppImage file into a shell script that "installs" the AppImage and set the icon and launcher in $HOME/.local/shared/icons and $HOME/.local/shared/applications. It works better, and the icon is ok on the dock too. It is an independent script so it can be used for anyone who likes this approach:

https://gist.github.com/mnesarco/baa2d49d9ec1b1edb41be7202cac352d

The generated installer script is 100% self-contained. So the final user still downloads a single file.

**Comment by ahsand97** [comment] 2022-03-06 15:58
I'm still confused, what would be the correct way to have an icon to the .AppImage binary itself?? without requiring to install any kind of daemon, a way that every file manager would show the icon just by downloading the AppImage file

**Comment by probonopd** [comment] 2022-03-06 17:45
Either you need a daemon like `appimaged` from https://github.com/probonopd/go-appimage/, or you need a file manager that natively supports it.

**Comment by Sytten** [comment] 2023-11-08 16:16
This is an old issue, but is this the expected behaviours?
I am fine with no icon on the filesystem, but I am wondering if we can set an icon for the dock.
<img width="72" alt="Screen Shot 2023-11-08 at 11 15 22 AM" src="https://github.com/AppImage/AppImageKit/assets/2366731/6a700348-8f02-4758-9dd6-57afd7fea08a">

**Comment by probonopd** [comment] 2023-11-08 17:32
You can get an icon for the filesystem by using a thumbnailer.
You can get an icon for the Dock by setting the window icon (e.g., `QWidget::setWindowIcon()` in Qt).

**Comment by Sytten** [comment] 2023-11-09 00:03
Yeah I updated tauri to the latest version and it seems to have fixed the issue. Thanks!

**Comment by xplshn** [comment] 2024-06-23 02:19
> Either you need a daemon like `appimaged` from https://github.com/probonopd/go-appimage/, or you need a file manager that natively supports it.

@probonopd Would you mind explaining how it works for "a file manager that natively supports it."? I am making a shell-based format that works like AppImages but also like the ape-loader of Cosmopolitan libC. Thanks!

**Comment by probonopd** [comment] 2024-06-29 09:04
For example, [Filer ](https://github.com/probonopd/filer )supports the AppImage file format natively.

**Comment by xplshn** [comment] 2024-06-29 12:11
So, do all other filers that show icons for AppImages do it the same way? Caja for example? Does it implement a handler? Or does its thumbnailer service do the work? I made a daemon called PELFd query the bundles by executing them with the parameters:
 `--pbundle_desktop`
 `--pbundle_pngIcon`
 `--pbundle_svgIcon`
 `--pbundle_xpmIcon`
And then it rewrites the .desktop file to contain the correct paths to the icons and executable file. Then it writes that to a log too and moves the files to their appropriate places, however, that only covers icons in menus, I wanted to add support for icons in file managers to...

**Comment by xplshn** [comment] 2024-06-29 12:19
Okay. I read the Thumbnail Managing Standard, now I understand (i think), I'll test it in OpenBSD before I push the changes to my [repo](https://github.com/xplshn/pelf). I hope I can get this format on par with AppImages soon and also be able to package QT/Python apps without recompilation. GTK seems to work well enough, but gschemes and other things need to be considered.

**Comment by nshiell** [comment] 2025-08-20 22:34
My build script has

```
...
./linuxdeploy-x86_64.AppImage \
    --appdir AppDir \
    -i ../artwork/database-dossier.png \
    -d ../artwork/database-dossier.desktop \
    --plugin conda \
    --custom-apprun ./AppDir/AppRun.sh \
    --output appimage
...
```

It's not showing the icon file in Dolphin (other AppImages are showing their icon files though)
Am I doing something wrong?
