### ISSUE TITLE
AppImage built on Trusty Travis CI doesn't run on Debian 8 or 9

### ISSUE THREAD

**Issue by vadi2** [AppImage/AppImageKit#434] opened 2017-07-23 09:46 UTC
[This AppImage](https://www.mudlet.org/download/Mudlet-3.3.1-linux-x64.AppImage.tar) is giving the following error on a 64bit Debian 9 VM: `cannot execute binary file: Exec format error`

Any ideas? The obvious architecture mismatch issue does not seem to be it.

Original ticket @ https://github.com/Mudlet/Mudlet/issues/1229.

**Comment by probonopd** [comment] 2017-07-23 09:58
A `.tar` file?!

**Comment by TheAssassin** [comment] 2017-07-23 10:08
It doesn't make much sense that it is in a tar archive. Since it is a single file, try to avoid the archiving step, and upload the AppImage as-is.

**Comment by vadi2** [comment] 2017-07-23 10:12
Github doesn't support uploading AppImages as-is :(

**Comment by probonopd** [comment] 2017-07-23 10:14
Only that it isn't even hosted on GitHub...

**Comment by probonopd** [comment] 2017-07-23 10:25
> Github doesn't support uploading AppImages as-is :(

It does, on GitHub Releases.

**Comment by vadi2** [comment] 2017-07-23 10:37
Does that affect it not running on Debian?

**Comment by probonopd** [comment] 2017-07-23 11:23
I don't know but I consider that "AppImage" to be broken because it is not an AppImage,

**Comment by vadi2** [comment] 2017-07-23 18:45
Okay here is a better one: https://transfer.sh/Ru1XW/Mudlet-3.3.1-linux-x64.AppImage

It still has the same issue running on Debian systems :confused:

**Comment by probonopd** [comment] 2017-07-23 18:46
Runs without problems on openSUSE LEAP 42.2.

**Comment by vadi2** [comment] 2017-07-23 18:52
Runs without problems on Ubuntu too. Neither are Debian...

I feel like there's no interest in actually helping solve the issue I'm having here.

**Comment by probonopd** [comment] 2017-07-23 18:55
I cannot reproduce this issue using `debian-live-8.6.0-amd64-xfce-desktop.iso`.

**Comment by itsTheFae** [comment] 2017-07-23 19:13
I get these errors when running a fresh install of both Debian 8.5 and Debian 9.0.1.  I installed both versions to separate VirtualBox VMs using a debian live installer image, 64-bit for both.   The installations are standard desktops, both xfce with the default configuration and package options. 

If you say the app image is running in debian live image, would there be a possible dependency issue here?  Something that is included in the live image that isn't installed by default for a standard/default Debian installation?

**Comment by probonopd** [comment] 2017-07-23 19:18
Yes, that could be the cause. But I don't know what.

**Comment by itsTheFae** [comment] 2017-07-23 19:31
I would be happy to provide just about any information you ask for in order to help figure this out.  
I'm way more clueless on this than you are, I think.  The error message isn't the most descriptive and I am not totally sure where or what else to check that would provide helpful information.

If there is a list of dependencies for AppImage, I can check which are/aren't installed and test which ones might be needed.  Could you produce this list of dependencies for me?  
If not, could you produce a list of the installed packages on your live image so I can compare those against what is installed in my Debian installations?

**Comment by probonopd** [comment] 2017-07-23 19:33
What does 
```
./Mudlet-3.3.1-linux-x64.AppImage --appimage-extract
```
say?

**Comment by itsTheFae** [comment] 2017-07-23 19:44
Trying your command line argument, I get the same error as trying to execute it normally. 
`bash: ./Mudlet-3.3.1-linux-x64.AppImage: cannot execute binary file: Exec format error`

**Comment by probonopd** [comment] 2017-07-23 19:51
Please post the output (first lines) of

```
file ./Mudlet-3.3.1-linux-x64.AppImage
strings ./Mudlet-3.3.1-linux-x64.AppImage | head -n 1
strace -f ./Mudlet-3.3.1-linux-x64.AppImage
```

**Comment by probonopd** [comment] 2017-07-23 19:59
Just to be 100% sure, does the same error happen when using https://bintray.com/probono/AppImages/download_file?file_path=Leafpad-0.8.18.1.glibc2.4-x86_64.AppImage?

**Comment by itsTheFae** [comment] 2017-07-23 20:27
Thanks for the help, and sorry for the bother.
Turns out the reporter uses only the GUI to extract the image via debian's "Extract Here" menu entry, which for some reason produces a second file that is a tar file but does not have a tar extension.  The file can't be run because it isn't the actual AppImage, its a damnable tar file. hahaha.  
_doh!_

**Comment by TheAssassin** [comment] 2017-07-23 20:29
Well, looks like we can close this issue then.

Next time, call `file` first, to get an interpretation of the magic number, as well as xxd or hexdump, as that might reveal the less obvious solutions already.

**Closed by TheAssassin** 2017-07-23 20:29 UTC

**Comment by probonopd** [comment] 2017-07-23 21:05
> Turns out the reporter uses only the GUI to extract the image via debian's "Extract Here" menu entry, which for some reason produces a second file that is a tar file but does not have a tar extension. The file can't be run because it isn't the actual AppImage, its a damnable tar file. hahaha.

It did the same thing for me, https://github.com/AppImage/AppImageKit/issues/434#issuecomment-317246288

__Pleeeeease don't put AppImages into archives like tar files.__ This is what happens.
