### ISSUE TITLE
What is the problem with QQ now?

### ISSUE THREAD

**Issue by gegewuwuwu** [AppImage/AppImageKit#551] opened 2017-11-27 01:12 UTC
I am Kevin from deepin, What is the problem with QQ now?

Can you provide wrong information or screenshots?

**Comment by probonopd** [comment] 2017-11-27 21:13
QQ is a 32-bit Windows executable. This is difficult because:

- [x] I need to figure out how to bundle WINE
- [x] I need to figure out how to bundle 32-bit binaries for use on 64-bit machines
- [x] I need to figure out how to make WINE use a read-only `$WINEPREFIX`
- [ ] I need to make it free of crashes
- [ ] I need to test it

But I am making some progress. It is really complicated, I need some more time.

Right now I am already getting the login screen on Ubuntu (without 32-bit libs or WINE installed on the system):

![1 zr2knzzzzbbh1nc1bbxkzw](https://user-images.githubusercontent.com/2480569/33289524-c72599b4-d3b7-11e7-87cc-4fd2d0da0170.gif)

It's a start...

**Comment by jingle0927** [comment] 2017-11-28 06:27
I've forwarded the question to the developer.

**Comment by probonopd** [comment] 2017-11-28 07:18
Some information [here](https://github.com/AppImage/AppImageKit/wiki/Bundling-Windows-applications).

**Comment by probonopd** [comment] 2017-11-28 07:36
Here is what I did so far:

* Install Wine on Ubuntu 16.04 as per the Ubuntu Wiki from the wine PPA
* It is in `/opt/wine-stable/` in both 64- and 32-bit variants
* Since QQ is a 32 bit executable, we need to use 32-bit wine and winelib
* To do that we need a 32-bit loader
* We have done that recently already for quasselcore... so how hard can it be? Hey, that was EASY!
* https://dl.winehq.org/wine-builds/ubuntu/pool/main/wine-stable-i386_2.0.3~trusty_i386.deb suitable as well?

http://tux.rainside.sk/deepin/pool/non-free/a/apps.com.qq.im.light/ <- contains wine directory, works WELL with that WINE

```
# For some reason need to install this into the SYSTEM so that we can copy it from /opt - need to find out why
# otherwise `wineserver` is missing
sudo dpkg --add-architecture i386 
wget https://dl.winehq.org/wine-builds/Release.key
sudo apt-key add Release.key
sudo apt-add-repository 'https://dl.winehq.org/wine-builds/ubuntu/'
sudo apt-get update
sudo apt-get install wine-stable winehq-stable 

mkdir QQ ; cd QQ
# wget -c https://dl.winehq.org/wine-builds/ubuntu/pool/main/wine-stable-i386_2.0.3~trusty_i386.deb # For whatever reason this does not work. Instead have to install it into the system and then copy it from /opt to opt/ - then wineserver is NOT missing
wget -c http://security.ubuntu.com/ubuntu/pool/main/g/glibc/libc6-i386_2.24-9ubuntu2.2_amd64.deb
wget -c http://tux.rainside.sk/deepin/pool/non-free/a/apps.com.qq.im.light/apps.com.qq.im.light_7.9.14308deepin3_i386.deb
wget -c http://mirrors.kernel.org/ubuntu/pool/universe/u/unionfs-fuse/unionfs-fuse_0.24-2.2ubuntu1_amd64.deb

mkdir QQ.AppDir ; cd QQ.AppDir
# dpkg -x ../wine*.deb .
# INSTEAD: cp /opt ... wine
dpkg -x ../libc6*.deb .
dpkg -x ../apps*.deb .
dpkg -x ../unionfs-fuse*.deb .

# Apparently we need this - still unclear why
# sed -i -e 's|/lib/ld-linux.so.2|./lib32/ld-2.24.so|g' ./opt/wine-stable/bin/wine # Not sure at all if this is a good idea
# Maybe we need a root helper to extract ld-linux to the system!

# Need to run it once so that Wine doesnt "update wine configuration" on each start
HERE="$(dirname "$(readlink -f "${0}")")"
WINEPREFIX="$HERE/opt/cxoffice/support/apps.com.qq.im.light/" \
"$HERE/lib32/ld-linux.so.2" --library-path "$HERE/lib32" "$HERE"/opt/wine-stable/bin/wine \
"$HERE/opt/cxoffice/support/apps.com.qq.im.light/drive_c/Program Files/Tencent/QQLite/Bin/QQ.exe" "$@"
# Manually press "cancel" on all installations

# Disabling Wine from updating wineprefix automatically
echo "disable" > "$HERE/opt/cxoffice/support/apps.com.qq.im.light/.update-timestamp" 

mkdir -p usr/lib/i386-linux-gnu

# On Deepin this works because there is already something there:
cp /usr/lib/i386-linux-gnu/* usr/lib/i386-linux-gnu/

cat > AppRun <<\EOF
#!/bin/bash
HERE="$(dirname "$(readlink -f "${0}")")"
RO_DATADIR="$HERE/opt/cxoffice/support/apps.com.qq.im.light/"
RW_DATADIR="$HOME/.QQ.unionfs"
export LD_LIBRARY_PATH=./lib32/:./usr./lib32/:./lib/i386-linux-gnu/:./usr/lib/i386-linux-gnu/:$LD_LIBRARY_PATH
mkdir -p $RW_DATADIR /tmp/QQ
$HERE/usr/bin/unionfs-fuse -o use_ino,nonempty,uid=$UID -ocow /tmp/QQ=RW:"$RO_DATADIR"=RO "$RW_DATADIR" || exit 1
WINEPREFIX="$RW_DATADIR" WINEDEBUG=-all \
"$HERE/lib32/ld-linux.so.2" --library-path "$HERE/lib32" "$HERE"/opt/wine-stable/bin/wine \
"$RW_DATADIR/drive_c/Program Files/Tencent/QQLite/Bin/QQ.exe" "$@"
killall $HERE/usr/bin/unionfs-fuse
EOF
chmod +x AppRun

./AppRun

sed -i -e 's|^Categories=.*|Categories=Network;Chat;|g' usr/share/applications/apps.com.qq.im.light.desktop
sed -i -e 's|^Exec=.*|Exec=AppRun|g' usr/share/applications/apps.com.qq.im.light.desktop
sed -i -e 's|^X-Created-By=.*||g' usr/share/applications/apps.com.qq.im.light.desktop
cp usr/share/applications/apps.com.qq.im.light.desktop .
cp usr/share/icons/hicolor/48x48/apps/apps.com.qq.im.light.png .

cd ..

wget https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage
chmod +x appimagetool-x86_64.AppImage 
ARCH=x86_64 ./appimagetool-x86_64.AppImage QQ.AppDir/ --verbose=2
./appimagetool QQ.AppDir/
```

__It runs only on the machine that it was produced on from where it uses 32-bit libraries.
Interestingly, Deepin has SOME of those preinstalled - enough to start our AppImage!__ However, we want this to work not only on Deepin, but also on other distributions. To fix this, we need to [bundle any and all 32-bit dependencies](https://github.com/AppImage/AppImageKit/wiki/Bundling-Windows-applications#2-bundle-any-and-all-32-bit-dependencies-1).

More research is needed.

**Comment by probonopd** [comment] 2017-11-28 23:56
I now have an AppImage basically working, but after some time QQProtect kicks in and seems to make the application stop working. More investigation needed.

**Comment by probonopd** [comment] 2017-11-29 00:44
AppImage is running now. But needs to be optimized.

![](https://user-images.githubusercontent.com/2480569/33351960-5e6899ca-d49e-11e7-87a2-8a845e2c5bd0.png)

**Comment by TheAssassin** [comment] 2017-11-29 00:46
@probonopd by the way, what does "Gamux" stand for?

**Comment by probonopd** [comment] 2017-11-29 01:00
Chinese instant messenger meets German distribution:

![](https://user-images.githubusercontent.com/2480569/33352402-f5417a60-d4a8-11e7-9167-de7fb59f4bff.png)

**Comment by jingle0927** [comment] 2017-11-29 01:22
@probonopd  What's the same problem with the screenshot under the deepin?

**Comment by jingle0927** [comment] 2017-11-29 01:42
1. Open the registry , the command `WINEPREFIX=$bottle wine regedit`
2. Import the registry file according to the content of the screenshot.

![_ _20171129093250](https://user-images.githubusercontent.com/26103116/33353566-612572dc-d4e9-11e7-8cec-61c5038ca38a.png)


[QQ_fonts.reg.zip](https://github.com/AppImage/AppImageKit/files/1512252/QQ_fonts.reg.zip)

**Comment by shouhuanxiaoji** [comment] 2017-11-29 10:39
@TheAssassin  "Gamux" = Game + Linux, a community about Linux games. they hope spread linux and opensource in china through offerting more games. and they have explored more than 4 years for offering same experiences in different distributions. the AppImage is very well in line with their goals. so they embrace AppImage. 
AppImage for Gamux = appImage for chinese linux user.

**Comment by jingle0927** [comment] 2017-11-30 05:07
`deepin@deepin:~/Desktop$ ./QQ-20171129-x86_64.AppImage 
wine: cannot find L"C:\\windows\\system32\\wineboot.exe"
Wine cannot find the ncurses library (libncurses.so.5).
Unable to update the static FcBlanks: 0x0600
Unable to update the static FcBlanks: 0x0601
Unable to update the static FcBlanks: 0x0602
Unable to update the static FcBlanks: 0x0603
Unable to update the static FcBlanks: 0x06dd
Unable to update the static FcBlanks: 0x070f
Unable to update the static FcBlanks: 0x2028
Unable to update the static FcBlanks: 0x2029
Unable to update the static FcBlanks: 0xfff9
Unable to update the static FcBlanks: 0xfffa
Unable to update the static FcBlanks: 0xfffb
`

**Comment by probonopd** [comment] 2017-11-30 06:22
@jingle0927 which distribution and version are you using? How can this be reproduced?

**Comment by jingle0927** [comment] 2017-11-30 06:57
@probonopd   deepin distribution  QQ_fonts.reg.zip ?

**Comment by jingle0927** [comment] 2017-11-30 06:59
`fc-cache -f `

then  is ok

![_deepin-terminal_20171130145829](https://user-images.githubusercontent.com/26103116/33418044-fd806f6a-d5de-11e7-8659-83ed1659f736.png)

**Comment by linweilian03** [comment] 2017-11-30 09:18
I find some problem in QQ AppImage.  After I close it and reopen it many times, I can't open QQ again. The message in the terminal:
Cannot run due to existing symlinks in /tmp (FIXME)

**Comment by KurtPfeifle** [comment] 2017-11-30 12:34
Do I need learn to read and write Chinese (and type it on my keyboard) in order to use this?    :-)
<sup>(I'm WILLING, but my brain may be too old by now...)</sup>

**Comment by probonopd** [comment] 2017-11-30 17:37
@KurtPfeifle there is also an (older?) International version which can do English, will probably be next on the list...

**Comment by probonopd** [comment] 2017-11-30 17:45
> Cannot run due to existing symlinks in /tmp (FIXME)

Need to 

```
rm /tmp/ld-linux.so.2
```

Needs to be fixed in the AppImage AppRun script.

**Comment by probonopd** [comment] 2017-11-30 17:47
About the fonts:
The registry entry just sets some Windows fonts to be replaced by some Linux fonts. But if the fonts are not installed in Linux, then it will not work. But I think it is OK because people who use Chinese will probably have Chinese fonts installed in their Linux OS.

**Comment by askme765cs** [comment] 2017-12-07 12:30
we can put windows fonts needed in the driver_c/windows/Fonts as well as Import the registry file
and then the problem can be solved .

**Comment by probonopd** [comment] 2017-12-07 17:41
Very good @askme765cs we should do that. Which Chinese fonts (under a permissive license) do you recommend?

**Comment by askme765cs** [comment] 2017-12-08 07:25
Since windows fonts are not allowed to be used or distributed out of the  Windows ,use opensource fonts may be a good ideal as a substitute.Place the fonts needed in  driver_c/windows/Fonts,so that it no longer needs there fonts exists in targeted system.
I suggest the wenquanyi project (https://sourceforge.net/projects/wqy/files/)  .This project supplies various of chinese opensource fonts.Fonts from this projects are uesd as the default chinese fonts in many linux distributions.
How to:
Step1
place the fonts you want to use in driver_c/windows/Fonts 
Step 2 modify and import the .reg file
##an example for chn_font.reg
'''
REGEDIT4
[HKEY_LOCAL_MACHINE\Software\Microsoft\Windows NT\CurrentVersion\FontLink\SystemLink]
"Lucida Sans Unicode"="wqy-microhei.ttc"
"Microsoft Sans Serif"="wqy-microhei.ttc"
"MS Sans Serif"="wqy-microhei.ttc"
"Tahoma"="wqy-microhei.ttc"
"Tahoma Bold"="wqy-microhei.ttc"
"SimSun"="wqy-microhei.ttc"
"Arial"="wqy-microhei.ttc"
"Arial Black"="wqy-microhei.ttc"
'''
replace fonts back following the "=" to fonts you prefer
use WINEPREFIX=$bottle wine regedit command to open the regedit and import it

**Comment by probonopd** [comment] 2017-12-09 13:18
@jingle0927 do you know liuchanghui@linuxdeepin.com? He has sent patches to WINE before, so maybe he could help us on solving this:

https://www.winehq.org/pipermail/wine-devel/2017-November/119944.html

> It's not possible in standard Wine, but you could probably hack
wine_exec_wine_binary() in libs/wine/config.c to add your special magic.

Here is the description of the problem:
https://www.winehq.org/pipermail/wine-devel/2017-November/119906.html

If we could patch WINE in the way suggested above, then we would not need these weird symlinks in `/tmp` anymore that I had to use as a quick-and-dirty workaround.

Thanks for your help.

**Comment by azubieta** [comment] 2018-11-24 02:02
Any update on this topic? Is it still required to keep the issue open?

**Comment by probonopd** [comment] 2018-11-24 11:33
Yes, shall be kept open until someone implements https://github.com/AppImage/AppImageKit/issues/551#issuecomment-350465625 in/for WINE, as that is the "proper" course of action. Thanks.

**Comment by probonopd** [comment] 2018-12-09 16:15
Looks like @Hackerl is close to mastering this one. :+1:

**Comment by ZetaoYang** [comment] 2018-12-15 12:17
@probonopd That's good!

**Comment by probonopd** [comment] 2018-12-15 12:43
Posted to https://www.winehq.org/pipermail/wine-devel/2018-December/136787.html

**Comment by Hackerl** [comment] 2018-12-19 09:02
I just tested it, it seems that there is no problem.

![image](https://user-images.githubusercontent.com/15811751/50209882-c6253c80-03af-11e9-95f3-643f1aea3e4f.png)

**Closed** 2023-02-17 02:02 UTC
