### ISSUE TITLE
no space left on device

### ISSUE THREAD

**Issue by mbogner** [AppImage/AppImageKit#639] opened 2018-01-27 02:03 UTC
Also got this problem. Ext4 without any space troubles.

```
manuel@fury:~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 17.10
Release:	17.10
Codename:	artful
manuel@fury:~$ uname -a
Linux fury 4.13.0-32-generic #35-Ubuntu SMP Thu Jan 25 09:13:46 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

manuel@fury:~$ df -h
Filesystem      Size  Used Avail Use% Mounted on
udev             24G     0   24G   0% /dev
tmpfs           4,8G   11M  4,7G   1% /run
/dev/sda6        63G   18G   42G  31% /
tmpfs            24G   53M   24G   1% /dev/shm
tmpfs           5,0M  4,0K  5,0M   1% /run/lock
tmpfs            24G     0   24G   0% /sys/fs/cgroup
/dev/sda2        96M   31M   66M  32% /boot/efi
tmpfs           4,8G   16K  4,8G   1% /run/user/121
tmpfs           4,8G  2,4M  4,8G   1% /run/user/1000

manuel@fury:~$ df -i
Filesystem      Inodes  IUsed   IFree IUse% Mounted on
udev           6162380    618 6161762    1% /dev
tmpfs          6169131   1252 6167879    1% /run
/dev/sda6      4194304 275643 3918661    7% /
tmpfs          6169131     26 6169105    1% /dev/shm
tmpfs          6169131      3 6169128    1% /run/lock
tmpfs          6169131     18 6169113    1% /sys/fs/cgroup
/dev/sda2            0      0       0     - /boot/efi
tmpfs          6169131     17 6169114    1% /run/user/121
tmpfs          6169131     44 6169087    1% /run/user/1000
```
Here an excerpt from my log:

```
Jän 27 02:27:37 fury systemd[1625]: appimaged.service: Main process exited, code=exited, status=1/FAILURE
Jän 27 02:27:37 fury systemd[1625]: appimaged.service: Unit entered failed state.
Jän 27 02:27:37 fury systemd[1625]: appimaged.service: Failed with result 'exit-code'.
Jän 27 02:28:37 fury systemd[1625]: appimaged.service: Service hold-off time over, scheduling restart.
Jän 27 02:28:37 fury systemd[1625]: Stopped AppImage daemon.
Jän 27 02:28:37 fury systemd[1625]: Started AppImage daemon.
Jän 27 02:28:37 fury appimaged[5383]: appimaged, continuous build (commit continuous-1-g0c9504f), build 1423 built on 2018-01-15 17:14:35 UTC
Jän 27 02:28:37 fury appimaged[5383]: No space left on device
Jän 27 02:28:37 fury systemd[1625]: appimaged.service: Main process exited, code=exited, status=1/FAILURE
Jän 27 02:28:37 fury systemd[1625]: appimaged.service: Unit entered failed state.
Jän 27 02:28:37 fury systemd[1625]: appimaged.service: Failed with result 'exit-code'.
Jän 27 02:29:37 fury systemd[1625]: appimaged.service: Service hold-off time over, scheduling restart.
Jän 27 02:29:37 fury systemd[1625]: Stopped AppImage daemon.
Jän 27 02:29:37 fury systemd[1625]: Started AppImage daemon.
Jän 27 02:29:37 fury appimaged[5608]: appimaged, continuous build (commit continuous-1-g0c9504f), build 1423 built on 2018-01-15 17:14:35 UTC
Jän 27 02:29:37 fury appimaged[5608]: No space left on device
Jän 27 02:29:37 fury systemd[1625]: appimaged.service: Main process exited, code=exited, status=1/FAILURE
Jän 27 02:29:37 fury systemd[1625]: appimaged.service: Unit entered failed state.
Jän 27 02:29:37 fury systemd[1625]: appimaged.service: Failed with result 'exit-code'.
Jän 27 02:30:37 fury systemd[1625]: appimaged.service: Service hold-off time over, scheduling restart.
Jän 27 02:30:37 fury systemd[1625]: Stopped AppImage daemon.
Jän 27 02:30:37 fury systemd[1625]: Started AppImage daemon.
Jän 27 02:30:37 fury appimaged[5866]: appimaged, continuous build (commit continuous-1-g0c9504f), build 1423 built on 2018-01-15 17:14:35 UTC
Jän 27 02:30:37 fury appimaged[5866]: No space left on device
Jän 27 02:30:37 fury systemd[1625]: appimaged.service: Main process exited, code=exited, status=1/FAILURE
Jän 27 02:30:37 fury systemd[1625]: appimaged.service: Unit entered failed state.
Jän 27 02:30:37 fury systemd[1625]: appimaged.service: Failed with result 'exit-code'.
Jän 27 02:31:37 fury systemd[1625]: appimaged.service: Service hold-off time over, scheduling restart.
Jän 27 02:31:37 fury systemd[1625]: Stopped AppImage daemon.
Jän 27 02:31:37 fury systemd[1625]: Started AppImage daemon.
Jän 27 02:31:37 fury appimaged[6087]: appimaged, continuous build (commit continuous-1-g0c9504f), build 1423 built on 2018-01-15 17:14:35 UTC
Jän 27 02:31:38 fury appimaged[6087]: No space left on device
Jän 27 02:31:38 fury systemd[1625]: appimaged.service: Main process exited, code=exited, status=1/FAILURE
Jän 27 02:31:38 fury systemd[1625]: appimaged.service: Unit entered failed state.
Jän 27 02:31:38 fury systemd[1625]: appimaged.service: Failed with result 'exit-code'.
Jän 27 02:32:38 fury systemd[1625]: appimaged.service: Service hold-off time over, scheduling restart.
Jän 27 02:32:38 fury systemd[1625]: Stopped AppImage daemon.
Jän 27 02:32:38 fury systemd[1625]: Started AppImage daemon.
Jän 27 02:32:38 fury appimaged[6552]: appimaged, continuous build (commit continuous-1-g0c9504f), build 1423 built on 2018-01-15 17:14:35 UTC
Jän 27 02:32:38 fury appimaged[6552]: No space left on device
Jän 27 02:32:38 fury systemd[1625]: appimaged.service: Main process exited, code=exited, status=1/FAILURE
Jän 27 02:32:38 fury systemd[1625]: appimaged.service: Unit entered failed state.
Jän 27 02:32:38 fury systemd[1625]: appimaged.service: Failed with result 'exit-code'.
Jän 27 02:33:38 fury systemd[1625]: appimaged.service: Service hold-off time over, scheduling restart.
Jän 27 02:33:38 fury systemd[1625]: Stopped AppImage daemon.
Jän 27 02:33:38 fury systemd[1625]: Started AppImage daemon.
Jän 27 02:33:38 fury appimaged[6560]: appimaged, continuous build (commit continuous-1-g0c9504f), build 1423 built on 2018-01-15 17:14:35 UTC
Jän 27 02:33:38 fury appimaged[6560]: No space left on device
Jän 27 02:33:38 fury systemd[1625]: appimaged.service: Main process exited, code=exited, status=1/FAILURE
Jän 27 02:33:38 fury systemd[1625]: appimaged.service: Unit entered failed state.
Jän 27 02:33:38 fury systemd[1625]: appimaged.service: Failed with result 'exit-code'.
Jän 27 02:34:38 fury systemd[1625]: appimaged.service: Service hold-off time over, scheduling restart.
Jän 27 02:34:38 fury systemd[1625]: Stopped AppImage daemon.
Jän 27 02:34:38 fury systemd[1625]: Started AppImage daemon.
Jän 27 02:34:38 fury appimaged[6568]: appimaged, continuous build (commit continuous-1-g0c9504f), build 1423 built on 2018-01-15 17:14:35 UTC
Jän 27 02:34:38 fury appimaged[6568]: No space left on device
Jän 27 02:34:38 fury systemd[1625]: appimaged.service: Main process exited, code=exited, status=1/FAILURE
Jän 27 02:34:38 fury systemd[1625]: appimaged.service: Unit entered failed state.
Jän 27 02:34:38 fury systemd[1625]: appimaged.service: Failed with result 'exit-code'.
```

I don't have more partitions on that system:

```
manuel@fury:~$ cat /etc/fstab 
# /etc/fstab: static file system information.
#
# Use 'blkid' to print the universally unique identifier for a
# device; this may be used with UUID= as a more robust way to name devices
# that works even if disks are added and removed. See fstab(5).
#
# <file system> <mount point>   <type>  <options>       <dump>  <pass>
# / was on /dev/sda6 during installation
UUID=08d8320c-5e55-4cc9-a8e5-cda02f9cb0f5 /               ext4    errors=remount-ro 0       1
# /boot/efi was on /dev/sda2 during installation
UUID=14CF-D21D  /boot/efi       vfat    umask=0077      0       1
/swapfile                                 none            swap    sw              0       0
```

And even the swap space is free ;-)

```
manuel@fury:~$ free -m
              total        used        free      shared  buff/cache   available
Mem:          48196        1924       44855         108        1416       45841
Swap:          2047           0        2047
```

Running the program manually:

```
manuel@fury:~$ appimaged 
appimaged, continuous build (commit continuous-1-g0c9504f), build 1423 built on 2018-01-15 17:14:35 UTC
No space left on device
```
The same with sudo:

```
manuel@fury:~$ sudo appimaged 
appimaged, continuous build (commit continuous-1-g0c9504f), build 1423 built on 2018-01-15 17:14:35 UTC
No space left on device
```

appimaged was installed from the debian package. I don't think that appimaged's error message is correct. Or at least I don't know what I'm missing. Any suggestions?

Same problem when installing it from the appimage file:

```
manuel@fury:~/.local/bin$ ./appimaged 
appimaged, continuous build (commit continuous-3-gb0ec1cb), build 1431 built on 2018-01-26 15:17:36 UTC
_________________________

-> Registering type 2 AppImage: /home/manuel/.local/bin/appimaged
_________________________
AppImage type: 2
Opening /home/manuel/.local/bin/appimaged as Type 2 AppImage
Closing /home/manuel/.local/bin/appimaged
squashfs based type 2 AppImage
Got root desktop: appimaged.desktop
Installing desktop file
No space left on device
```

**Comment by TheAssassin** [comment] 2018-01-27 09:35
Closing as duplicate of #617.

**Closed by TheAssassin** 2018-01-27 09:35 UTC
Labels: duplicate
