### ISSUE TITLE
Prevent appimage-extract from doing icon symlink

### ISSUE THREAD

**Issue by dguayrobotiq** [AppImage/AppImageKit#834] opened 2018-08-02 13:01 UTC
I have to use `./my_app.AppImage --appimage-extract` to run my app in my case because we are working on an old system. I'd like to do this and run the app from a USB key. 

When I run `./squashfs-root/AppRun`, since I'm on a USB key, it cannot do the symlink for the icon. Is there a way to deactivate it? I don't need this icon.

**Comment by TheAssassin** [comment] 2018-08-02 14:06
@dguayrobotiq does

> since I'm on a USB key

mean you use some inferior Microsoft-invented filesystem like FAT32?

Anyway, there is no way to make those extracted icons copies. The files shall be extracted as they are in the image.

To work around this, you could use something like `cd /tmp && /media/user/myusbdisk/my.AppImage --appimage-extract`.

**Comment by probonopd** [comment] 2018-08-02 19:49
I have to admit that I, too, use that "inferior Microsoft-invented filesystem" to store my AppImages. But I run them directly from there, without unpacking them, and that works well for me.

**Comment by dguayrobotiq** [comment] 2018-08-02 19:58
@probonopd We are working with an old system which doesn't have fuse activated by default and we can't recompile the kernel or make changes really. I have to extract (and run) the AppImage from a FAT32 USB key.

**Comment by probonopd** [comment] 2018-08-02 20:01
So you are saying we should check the target filesystem during extraction, and extract a copy rather than a symlink on a FAT32 filesystem? That would not even work in many cases, namely it would break in all cases in which the payload application loads resources from a path relative to itself. So not something we can support, at least I can't think of a good way to do it.

**Comment by dguayrobotiq** [comment] 2018-08-02 20:25
@probonopd We don't really have control over which USB stick will be used. My idea was to just ignore that symlink step since I don't need an icon :)

**Comment by dguay** [comment] 2018-08-03 01:51
@TheAssassin We're tried but we really need to start the app from the USB key for different reason. We are looking into other alternative (like makeself) but thank you both !

**Comment by TheAssassin** [comment] 2018-08-03 10:51
@dguay why can't you extract the files somewhere in advance and copy them over to the USB stick? You don't want to extract the files on every invocation, it's super inefficient.

**Comment by probonopd** [comment] 2018-08-03 18:05
> When I run ./squashfs-root/AppRun, since I'm on a USB key, it cannot do the symlink for the icon. Is there a way to deactivate it? I don't need this icon.

Are you saying just because it can't extract the icon, it extracts nothing at all? That'd be not optimal indeed. It should just skip that icon, print an error message, but extract the rest.

But keep in mind that other apps may use symlinks for more critical stuff than just icons.

**Comment by dguayrobotiq** [comment] 2018-08-03 18:13
@probonopd It stops extracting and I get the error `symlink error`

**Comment by probonopd** [comment] 2018-08-03 18:30
Ah, I see. We should print the symlink error and continue extracting then. Agree @TheAssassin?

**Comment by TheAssassin** [comment] 2018-08-07 19:38
@probonopd  I'm not really a fan of this idea

@dguayrobotiq hard to estimate. I think we'd need an icon specific exception somewhere in a complex piece of code.

**Comment by dguayrobotiq** [comment] 2018-08-07 19:45
@TheAssassin we're looking to use AppImage with `electron-builder`'s auto-updater

**Comment by TheAssassin** [comment] 2018-08-07 19:47
Wait, you said the problem is with "old systems", right? What's the exact issue you have? Are you just proposing to add another workaround to AppImageKit to make your workaround work? I'd like to know whether we could fix the original issue so that the AppImages just run.

**Comment by dguayrobotiq** [comment] 2018-08-07 19:50
@TheAssassin First issue is I can't make FUSE work on the system. I've tried many things and the only possible solution would involve recompiling the kernel which we can't do. So we went the `--appimage-extract` route. 

We can't extract (or move after extract) the files from AppImage's extract on the system because there is not enough space... That's why we need to run it from the USB FAT32 key

**Comment by TheAssassin** [comment] 2018-08-07 19:51
I see... okay, well, I'll try to get to working on this then.

**Comment by dguayrobotiq** [comment] 2018-08-07 19:57
@TheAssassin Thanks for your help really appreciate it ! Hope this is not something too much complex.

**Comment by TheAssassin** [comment] 2018-08-07 20:07
I don't think so. But I am always quite reluctant to adding more exceptions for edge cases, this just adds maintenance overhead.

**Comment by TheAssassin** [comment] 2018-08-08 17:38
I looked into this, and it's a bit more complex than expected. squashfs provides only the name of the symlink's target on extraction. There's no reference to the target's inode which could be used to create a copy immediately, but only said path. This is not a limitation in its code, but actually a sane design decision, since a symlink may as well point outside a squashfs image.

Therefore, in order to implement this workaround we have to create a list of symlinks to create (including their targets) while traversing the squashfs tree, and after all files have been extracted, we need to copy those files into position. We have to do it this way, as the symlink targets may or may not have been extracted before the symlink was found in the squashfs tree.

We also need to make sure only to copy files that are inside the squashfs image, and not outside. Otherwise, some annoying person may compose an AppImage with thousands of symlinks to large system files, and tell people to extract. You can imagine what would happen.

Note to self: call `readlink` on symlink targets before copying the files, the symlinks may be symlinks to other symlinks, etc.

**Comment by probonopd** [comment] 2018-08-08 21:12
I think the poster would already be happy if extraction, when encountering an error, would continue rather than abort. Correct @dguayrobotiq?

**Comment by TheAssassin** [comment] 2018-08-08 21:24
Done. The other, half finished changes have been pushed to https://github.com/AppImage/AppImageKit/tree/issue-834. Let's wait for @dguayrobotiq's reply.

**Comment by dguayrobotiq** [comment] 2018-08-08 21:36
Yes exactly ! Just ignoring the error should be fine I hope ! I'm building the AppImage with `electron-builder`. Would they need to update something?

**Comment by TheAssassin** [comment] 2018-08-09 02:05
@dguayrobotiq well they just need to rebuild the AppImage with the latest version of the runtime. Just make sure your build tool, whatever it is, uses an up to date copy of the runtime.

We are not going to merge that branch. Closing as resolved.

**Closed by TheAssassin** 2018-08-09 02:05 UTC
Labels: enhancement, pr-welcome

**Comment by TheAssassin** [comment] 2018-08-09 16:37
@develar can you please update to using the latest runtime? Thanks.

**Comment by develar** [comment] 2018-08-09 16:52
@TheAssassin Problem is that you didn't release AppImage. Latest release on https://github.com/AppImage/AppImageKit/releases is `Nov 9, 2017`. There is "Continuous build", but it is continuous, not release. Last time when I checked should I update or not, I decided to wait next release.

**Comment by TheAssassin** [comment] 2018-08-09 16:57
@develar we don't do "releases", we follow the continuous deployment approach. CC @probonopd

**Comment by develar** [comment] 2018-08-09 17:03
@TheAssassin For me not clear when I should update and why. Releases and changelog will make it clear :) I will do update now.
