### ISSUE TITLE
"file command is missing but required, please install it"

### ISSUE THREAD

**Issue by develar** [AppImage/AppImageKit#691] opened 2018-03-05 07:45 UTC
Not clear for me why this command is required. It is not convenient to install bunch of tools in addition to AppImage :) I don't see usages of this command in the source code.

**Comment by KurtPfeifle** [comment] 2018-03-05 08:33
@develar:

If you didn't find it in the source code: in which context did you experience this?

If it is with a specific AppImage, can you give a link to it?

What you could do for further narrowing down the problem with an AppImage:

1. Extract the AppImage payload:

    `the.AppImage --appimage-extract`     # For type 2 AppImages

    The payload now is an AppDir, in a subdirectory named `./squashfs-root`.

1. Run the payload as an AppDir:

    `cd ./squashfs-root ; ./AppRun`

    If the AppImage was correctly composed following all of the [AppImage Specifications](https://github.com/AppImage/AppImageSpec/blob/master/draft.md) it should run just the same. You however now have access to all its individual files inside the AppImage.

**Comment by TheAssassin** [comment] 2018-03-05 11:50
Duplicate of #590.

**Closed by TheAssassin** 2018-03-05 11:50 UTC
Labels: duplicate

**Comment by probonopd** [comment] 2018-03-05 21:19
@develar it is used to determine the architecture of the AppImage, the code is here:

https://github.com/AppImage/AppImageKit/blob/80eb15473dbb9287f4eab4ef431cc1d0b658b958/src/appimagetool.c#L331-L341
