### ISSUE TITLE
[AppImageUpdate] Ask for root password if needed

### ISSUE THREAD

**Issue by probonopd** [AppImage/AppImageKit#268] opened 2016-11-05 19:08 UTC
Ask for root password if needed, similar to what Etcher does.

**Comment by abhay44** [comment] 2017-02-12 17:22
@probonopd Can you tell me when do you want to ask the root password and what for ?

**Comment by probonopd** [comment] 2017-02-12 19:13
Imagine an AppImage is stored on a location in the filesystem like `/opt`where normal users cannot write. If AppImageUpdate is ran on such a file, it would be useful to ask the user for root permissions and proceed, instead of just saying that the file could not be written.

**Comment by abhay44** [comment] 2017-02-13 09:03
@probonopd Running build.sh with sudo(if required) does the work? or do we have to define a separate mechanism inorder to do so?

**Comment by probonopd** [comment] 2017-02-13 17:50
`build.sh` is being executed at build time. This ticket is about running at _runtime_. So I don't think running build.sh with sudo is really related to the problem described in my use case above.

**Comment by abhay44** [comment] 2017-02-13 20:20
So, you want me to place the code that does the whole work in `AppRun.c` ? Am I correct ? If no, can you correct me?

**Comment by probonopd** [comment] 2017-02-13 20:24
No, the code would need to go into the payload application, which is `appimageupdategui` in this case. Its souce code is [here](https://github.com/probonopd/AppImageKit/tree/master/appimageupdategui).

**Comment by abhay44** [comment] 2017-02-14 07:28
@probonopd I think they used `sudo-prompt` which is a thirdparty library inorder to ask for a root password.

**Comment by probonopd** [comment] 2017-02-14 07:46
Can we do the same? What would it take?

**Comment by abhay44** [comment] 2017-02-14 08:22
`sudo-prompt` is written in JavaScript. So, I don't think that will be useful for us. Probably @jviotti suggestion would help us. or do you have any other idea?

**Comment by probonopd** [comment] 2017-02-14 19:05
What does `sudo-prompt` do to actually become root`Call `sudo`?

**Comment by abhay44** [comment] 2017-02-14 19:37
Yes, that's a good option. But, I am little bit confused where does this whole code go into. Could you give me a hint where to place this code?

**Comment by probonopd** [comment] 2017-02-14 19:39
Most likely into the appimageupdate script, which would check for write permissions in the target directory and if they are missing, would ask for root permissions?

**Comment by abhay44** [comment] 2017-02-14 19:46
Ya, that looks good. But, I am asking whether into vala script or another shell script?

**Comment by probonopd** [comment] 2017-02-14 19:54
Vala sounds right but this is the part where I am not sure to best fit it in.

**Comment by abhay44** [comment] 2017-02-14 20:00
`appimageupdategui` is a graphical application right? `pkexec` can't run without having a policykit installed in some directory. Check [http://www.webupd8.org/2015/03/how-to-run-gedit-and-nautilus-as-root.html](url).So, what's your take on it?

**Comment by probonopd** [comment] 2017-02-14 20:07
policykit is assumed to be part of the base system (distribution). Yes, `appimageupdategui` is a graphical application. It is the frontend (progress bar dialog) to the `appimageupdate` bash script.

**Comment by jviotti** [comment] 2017-02-15 14:40
Hey there! So here's is what we currently do:

For UX purposes, we need the main application to be executed *without* root permissions. The application then forks itself after asking for permissions (using `sudo-prompt`), which causes the AppImage to get re-mounted to a new location, this time as `root`.

Showing the elevation dialogs from JavaScript is particularly tricky, but since this project is written in C, you have access to the native OS APIs, which makes this way easier.

I guess the question is how you would go about automating this, given that for most use cases, the application should ask elevation only when its needed (and not at startup).

**Comment by Israel-** [comment] 2017-08-25 21:20
Hi I want to use pkexec in one of my AppImages
The desktop file uses
Exec=pkexec  _program_
But I cannot fully figure out how to work things out so that it will all work nicely in the [AppImage desktopintegration](https://raw.githubusercontent.com/AppImage/AppImageKit/master/desktopintegration)

**Anyhow** if you need a polkit file for something they are super easy to create
install this file as /usr/share/polkit-1/actions/org.freedesktop.policykit.$EXEC
Change:
$EXEC to the executable
$NAME to the Name
$ICON to the icon (can be relative name)
```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE policyconfig PUBLIC  "-//freedesktop//DTD PolicyKit Policy Configuration 1.0//EN"  "http://www.freedesktop.org/standards/PolicyKit/1/policyconfig.dtd">
<policyconfig>
	<action id="org.freedesktop.policykit.$EXEC">
		<description>$NAME</description>
		<message>Authentication is required to edit system files</message>
		<icon_name>$ICON</icon_name>
		<defaults>
			<allow_any>auth_admin</allow_any>
			<allow_inactive>auth_admin</allow_inactive>
			<allow_active>auth_admin</allow_active>
		</defaults>
		<annotate key="org.freedesktop.policykit.exec.path">/usr/bin/$EXEC</annotate>
		<annotate key="org.freedesktop.policykit.exec.allow_gui">true</annotate>
	</action>
</policyconfig>
```
Then change the desktop file to
```desktop
Exec=pkexec $EXEC
```

**Comment by probonopd** [comment] 2017-08-25 21:35
Only that we cannot write to `/usr/share`...

**Comment by Israel-** [comment] 2017-08-25 21:43
@probonopd Ahhhh I see... that is a problem then.
I am not sure how that could be accomplished
So... we devs cannot make a pkexec capable thing... but there could be a potential work around
Make a generic appimage polkit file where the exec is AppImage.client
 and then the wrapper could take care of making a symlink
```sh
ln -s /usr/bin/AppImage.client $EXEC
```
But this is problematic

**Comment by probonopd** [comment] 2017-08-25 21:59
@jviotti has described what needs to be done, and he has done it for his application, Etcher. Works very well for me.

**Comment by TheAssassin** [comment] 2018-07-26 18:32
Duplicate of https://github.com/AppImage/AppImageUpdate/issues/1.

**Closed by TheAssassin** 2018-07-26 18:32 UTC
Labels: enhancement
