### ISSUE TITLE
[Feature] DragonFly BSD Support

### ISSUE THREAD

**Issue by ghbjklhv** [AppImage/AppImageKit#962] opened 2019-05-20 02:59 UTC
**Description** I would like to discuss the possibility of Appimages possibly being extended to work on DragonFly BSD. As well as implementing Appimages to run on DragonFly BSD and similar forks.

Related to #98 , which is more about a FreeBSD implementation.

_____________________

Want to support this issue? Post a [bounty on it](https://www.bountysource.com)! We accept bounties via [BountySource](https://www.wikipedia.org/wiki/Bountysource).

**Comment by probonopd** [comment] 2019-05-20 06:15
See if you can compile `runtime.c`, if yes the it might be possible.

**Comment by TheAssassin** [comment] 2019-05-20 11:34
Duplicate of #98.

#98 is about all BSDs, not just FreeBSD. See the title.

**Closed by TheAssassin** 2019-05-20 11:34 UTC
Labels: deprioritized

**Comment by ghbjklhv** [comment] 2019-05-24 23:32
@TheAssassin Aye, could you reopen this issue?
Although, the title for #98 is about all BSD OSes this just simply isn't possible.
There are too many Oses for BSD with many differences.

**Comment by probonopd** [comment] 2019-05-25 05:58
The point is, no one is working on this for _any_ BSD, so we don't need to open a ticket for _every_ BSD.
