### ISSUE TITLE
Payload software may hang when not intercepting SIGCHLD properly

### ISSUE THREAD

**Issue by dimbleby** [AppImage/AppImageKit#812] opened 2018-07-08 13:20 UTC
As originally reported at neovim/neovim#8104

To reproduce
* Get neovim appimage: ` curl -LO https://github.com/neovim/neovim/releases/download/nightly/nvim.appimage`
* `chmod +x nvim.appimage`
* `./nvim.appimage -u NORC`
* `:term` (opens a terminal inside neovim)
* `i` (enter insert mode)
* `<C-d>` (send EOF)

At this point the process hangs.  (If it wasn't hung, you'd be able to type `<Esc>:q<CR>` to exit.)

This hang doesn't happen in the unpacked appimage (`./nvim.appimage --appimage-extract; ./squashfs-root/AppRun -u NORC` etc)

Over in that issue the suggestion was to use `strace` to debug - but as noted over there, `strace -f ...` *also* hangs on the packed appimage.  Since that `-f` is all about following child processes I wonder whether this isn't in fact somehow the same bug?  But that might be too much of a leap.

**Comment by probonopd** [comment] 2018-07-08 13:41
Does this also happen with `sudo strace -f ...AppImage`?

**Comment by dimbleby** [comment] 2018-07-08 15:51
I think you're drawing attention to the `sudo`?  Yes, the `strace` command still hangs when run as root.

(Does this not reproduce for you?  As and when you are able to look at this, it'll be much more efficient to answer such questions yourself than by having me act as a slow terminal, and one prone to misunderstandings at that!  

Of course if my steps above do not reproduce the problem for you then I'll be glad to help try and figure out the difference).

**Comment by probonopd** [comment] 2018-07-08 18:12
Not in front of a Linux machine right now, but can you confirm that the AppImage is still mounted at the point when it hangs? Or may it prematurely have exited?

**Comment by TheAssassin** [comment] 2018-07-10 10:00
@dimbleby can you provide an strace log? It'd be interesting to see which syscall makes the AppImage hang, as the fact that the strace process hangs is not very surprising.

**Comment by dimbleby** [comment] 2018-07-10 10:31
Once again I'd encourage interested parties to set up their own repro - or let me know that the steps I gave do not reproduce the problem for them.  That'll be *much* faster than routing all questions through me.

But anyway: for this one, we already have what you're asking for from the original neovim issue - [here](https://github.com/neovim/neovim/issues/8104#issuecomment-397822147).

**Comment by TheAssassin** [comment] 2018-07-10 10:37
@dimbleby as you reported the issue here, you must expect that you are contact person for the upstream project. You should probably make the participants of the other issue contact us here if you're not personally interested in this issue, then we'll talk to them.

**Comment by dimbleby** [comment] 2018-07-10 10:47
Very happy to handle non-trivial questions or, for instance, to help you set up your own repro in case my steps are not sufficiently explicit or just don't work for you.

Less happy - but, per this thread, willing! - to handle trivial questions that could easily be answered by y'all setting up your own repro.  It just seems like it would be more efficient for both of us to skip the middle man.

**Comment by TheAssassin** [comment] 2018-07-10 11:06
@dimbleby the problem is the limited amount of time available to maintain not only AppImageKit but all the AppImage related projects. Therefore we need to delegate some things to the reporters.

Regarding the strace output, there's no useful information in them, so yes, the only way to debug this is probably to try to reproduce this issue in an isolated environment. I'm not 100% sure what this `-u NORC` is supposed to do, but from the strace output it seems like it's trying to write something into the mounted AppDir, which is not possible because AppImages are mounted read-only. Perhaps nvim's error handling isn't very good in this scenario. But that's just my best guess right now. A link a link on those CLI parameters would probably help.

**Comment by dimbleby** [comment] 2018-07-10 11:21
Yes, well, we all are busy...

`-u NORC` tells `neovim` not to load `vimrc` files. which typically contain a bunch of user customisation - it's standard when hitting `vim` or `neovim` problems to do this so as to rule out the problem being something specific to the user environment.  See [here](https://github.com/neovim/neovim/blob/13bdc21faf936f7af7511b5001628ee547cc215b/runtime/doc/starting.txt#L94).

I'd guess that this is unlikely to cause `neovim` to try and write anything - though that doesn't rule out that it might be trying to write something anyway.

However, I am very not familiar with `neovim` internals.   (My involvement in this issue is really just as someone who has hit the problem and would like to see it fixed).  If something like that does look like being the problem - we'll likely need to ask one of the maintainers.

**Comment by TheAssassin** [comment] 2018-07-10 23:09
I see, `NORC` is probably harmless. I can confirm that nvim starts to hang (

**Comment by TheAssassin** [comment] 2018-07-10 23:14
Closing issue as invalid. Please reopen if you disagree.

**Comment by dimbleby** [comment] 2018-07-11 08:13
I'm not seeing where neovim writes inside the appimage.  Here are all of the files that are ever opened in that strace:

```
$ grep "open(" unnamed.txt
6384  open("/etc/ld.so.cache", O_RDONLY|O_CLOEXEC) = 3
6384  open("/lib/x86_64-linux-gnu/libpthread.so.0", O_RDONLY|O_CLOEXEC) = 3
6384  open("/lib/x86_64-linux-gnu/libz.so.1", O_RDONLY|O_CLOEXEC) = 3
6384  open("/lib/x86_64-linux-gnu/libdl.so.2", O_RDONLY|O_CLOEXEC) = 3
6384  open("/lib/x86_64-linux-gnu/libc.so.6", O_RDONLY|O_CLOEXEC) = 3
6384  open("/proc/self/exe", O_RDONLY)  = 3
6384  open("/etc/ld.so.cache", O_RDONLY|O_CLOEXEC) = 3
6384  open("/lib/x86_64-linux-gnu/libfuse.so.2", O_RDONLY|O_CLOEXEC) = 3
6385  open("/home/vagrant/t/nvim.appimage", O_RDONLY) = 3
6385  open("/dev/null", O_RDWR)         = 5
6385  open("/tmp/.mount_nvim.aMVe9H7", O_RDONLY|O_NONBLOCK|O_DIRECTORY|O_CLOEXEC) = 5
6385  open("/dev/fuse", O_RDWR)         = 5
6386  open("/dev/null", O_RDWR)         = 8
6384  open("/tmp/.mount_nvim.aMVe9H7", O_RDONLY <unfinished ...>
6384  open("/etc/ld.so.cache", O_RDONLY|O_CLOEXEC <unfinished ...>
6384  open("/lib/x86_64-linux-gnu/librt.so.1", O_RDONLY|O_CLOEXEC <unfinished ...>
6384  open("/lib/x86_64-linux-gnu/libpthread.so.0", O_RDONLY|O_CLOEXEC <unfinished ...>
6384  open("/lib/x86_64-linux-gnu/libdl.so.2", O_RDONLY|O_CLOEXEC <unfinished ...>
6384  open("/lib/x86_64-linux-gnu/libm.so.6", O_RDONLY|O_CLOEXEC <unfinished ...>
6384  open("/lib/x86_64-linux-gnu/libutil.so.1", O_RDONLY|O_CLOEXEC <unfinished ...>
6384  open("/lib/x86_64-linux-gnu/libgcc_s.so.1", O_RDONLY|O_CLOEXEC <unfinished ...>
6384  open("/lib/x86_64-linux-gnu/libc.so.6", O_RDONLY|O_CLOEXEC <unfinished ...>
```

Do any of these look suspicious?  

What other possibilities might "etc" cover?  ie what other tasks are possible in general, possible in an unpacked appimage, but disallowed in a packed appimage?

**Comment by TheAssassin** [comment] 2018-07-11 10:04
@dimbleby no, this doesn't look suspicious, I was just guessing since nvim tries to write to a file descriptor 4. This is not one of the standard file descriptors (1-3), and could be a file, or maybe a pipe. At first I thought it might be the terminal's input pipe to which it tries to write which gets filled up and then blocks the process, but as the AppImage's contents work when extracted, I assumed that it were writes to the contents, i.e., a file. But only the nvim devs can tell you what FD 4 is in this case.

Any sort of modification to the files in an AppImage is not possible. Files may not be written to or moved or copied or whatever.

**Comment by dimbleby** [comment] 2018-07-11 10:14
Line 93 is before neovim has even been exec'd - that happens at line 193.  If that's really what's happening, then this is surely back in appimage's court?

**Comment by dimbleby** [comment] 2018-07-11 10:31
I also don't understand what's happening with that FD 4.  But do we agree that it's happening before the neovim app has even started?  Shall we re-open this issue?

**Comment by TheAssassin** [comment] 2018-07-11 12:55
I am still quite sure this doesn't have anything to do with the runtime but is a neovim specific issue. I'm missing some neovim devs here. We can reopen this issue, but I won't be able to invest much more time into this for now. Perhaps a neovim dev can explain some of the behavior.

**Comment by probonopd** [comment] 2018-07-12 05:41
Agree, we need someone who knows what neovim is doing there.

**Comment by dimbleby** [comment] 2018-07-12 07:59
We can certainly ask someone, but what questions do we have?  

(In the trail above we've focused on "what's going on with that FD 4?" - but, while we don't have the answer, we have established that this is nothing to do with neovim.)

**Comment by TheAssassin** [comment] 2018-07-12 09:46
> we have established that this is nothing to do with neovim

No, we have not, that's the point.

**Comment by dimbleby** [comment] 2018-07-12 09:49
As above, these writes start happening before neovim has even been exec'd.  

* The first is at line 165 (also 169, 173, etc)
* neovim is exec'd at line 193

What am I missing?

**Comment by TheAssassin** [comment] 2018-07-12 09:51
I assume the strace log is broken due to the point nvim is run as a subprocess (i.e., fork and exec).

> An FD 4 doesn't even exist, but it's written to. I'm not sure how strace behaves when an exec*(...) call is made, I think we'd need an strace of the nvim binary in the AppImage.
>
> https://github.com/AppImage/AppImageKit/issues/812#issuecomment-404121910

**Comment by dimbleby** [comment] 2018-07-12 21:50
Looks like I have a fix for this in neovim - neovim/neovim#8737.  The issue seems to be a `waitpid(-1, ...)` catching `SIGCHLD`s that weren't really wanted - presumably stopping them from going to someone else.

I guess this is a classic interaction bug: neovim was just fine using this general `waitpid()` until it was put into the appimage environment - but I imagine you'll consider that appimage isn't doing much wrong either!

However, here's another very similar issue from another project: https://patchwork.kernel.org/patch/9949491/

Suggest: it would be nice to find a place to document that to be appimage-compatible, apps must not catch more `SIGCHLD` than they need.  Maybe future travellers will find the road easier.

Thanks for your patience; I'll leave it to you to close this out when you're happy you've done all that you want to do with it.

**Comment by TheAssassin** [comment] 2018-07-12 22:39
Big thanks for the detailed analysis, really a great job, I wouldn't ever have thought of that. Well, as you say "must not catch more than they need", it seems like a "meant well isn't done well" issue. nvim clearly tries to do more than necessary, and they apparently didn't expect to ever be run as a subprocess like the AppImage runtime calls them.

Now, I agree that this is AppImageKit's fault to some extent. I guess if we improved the way the subprocess is created (i.e., more shell-ish, because shells are processes and nvim will be a subprocess of those processes, too), we could make sure this won't happen again.

I'll leave the issue open, but will try to find a better title. Thanks for the link, too, I'll check it out.

**Comment by probonopd** [comment] 2018-07-13 06:03
>  I guess if we improved the way the subprocess is created (i.e., more shell-ish, because shells are processes and nvim will be a subprocess of those processes, too), we could make sure this won't happen again.

Do we want this though? When writing `runtime.c` I intentionally avoided launching shells to minimize the number of running processes on the system.

**Comment by probonopd** [comment] 2018-07-13 06:13
> Suggest: it would be nice to find a place to document that to be appimage-compatible, apps must not catch more SIGCHLD than they need. Maybe future travellers will find the road easier.

Thanks @dimbleby, added a section to https://github.com/AppImage/AppImageKit/wiki/Creating-AppImages#troubleshooting

**Comment by TheAssassin** [comment] 2018-07-13 13:28
@probonopd I don't want to start a shell, but I want to fix the tty and signal handling so that such situations can be avoided in the future. Apparently, a shell can handle the issue @dimbleby described.

Don't get me wrong, using a shell wrapper might actually solve such issues, but we don't know for sure whether that'd fix the bug, and shells are always risky (it's possible to use them securely, e.g., Python implements the sort of escaping required for that purpose).

This is not a priority at all, this specific bug is _really_ rare, I'd say.

**Comment by probonopd** [comment] 2018-07-13 17:15
I'd say, its so rare that it should be handled in a custom AppRun script/executable for those few apps that might need it. I think it's outside the scope of `runtime.c` which we intentionally want to keep as small and generic as possible.

**Comment by TheAssassin** [comment] 2018-07-13 17:18
Making the runtime behave more transparently and also robust is _really_ worth investing time. It won't add any real complexity if written properly.

**Comment by probonopd** [comment] 2018-07-13 17:29
And it won't increase the number of running processes on the system, hence increasing clutter in the output of `ps ax`? I still think the issue discussed here is an issue of the payload application and not of AppImage and can be fixed by changing the payload application. Similar to payload applications that use hardcoded paths in `/usr` rather than paths relative to the main binary. Things we _can_ hack around but _shouldn't_. Hacking around this sort of things was something we had to do when AppImage was targeting _users_ rather than _application developers_. That model did not work, and now that we are working with  _application developers_ we can assume that they work their part, too, to make AppImages great.

**Comment by TheAssassin** [comment] 2018-07-13 17:33
@probonopd _again_, I don't want to add a shell there but fix the subprocess handling code (stuff like TTYs and pipes and signal handling/forwarding and such stuff). And actually I don't want to do that myself, please see the labels which say "deprioritized" and "pr-welcome".

**Comment by dimbleby** [comment] 2018-07-13 21:17
So looking back now that we know more about the broken case, I see that with 'bad' neovim we get a process tree like this:

```
$ ps -ef | grep appimage
dch      14288 13974  0 22:12 pts/6    00:00:00 ./nvim.appimage
dch      14289 14288  0 22:12 pts/6    00:00:00 [nvim.appimage] <defunct>
dch      14291     1  0 22:12 ?        00:00:00 ./nvim.appimage
```

The defunct process is the one that later caused neovim to hang: neovim does a `waitpid(-1)` and instead of learning about a child that it cares about it learns about one that it doesn't care about - and then never asks again.

I *think* that the defunct process comes from [this](https://github.com/AppImage/AppImageKit/blob/8e5936838e3df1e4b5b0e35655d3c5e38052c421/src/runtime.c#L519) `fork()`.

I wonder if the fix is as simple as adding `waitpid(pid, NULL, 0)` [here](https://github.com/AppImage/AppImageKit/blob/8e5936838e3df1e4b5b0e35655d3c5e38052c421/src/runtime.c#L562), making AppImage explicitly responsible for reaping its own child.

(I confess I'm confused about what the keepalive pipe is doing in that code!)

**Comment by TheAssassin** [comment] 2018-07-13 21:20
@dimbleby I honestly don't know, I didn't write that code. But since the `waitpid` call seems like a really good idea. Would you be willing to send a PR? Then, we can simply test it with nvim, by building a new AppImage with the new runtime.

**Comment by TheAssassin** [comment] 2018-07-13 21:38
Sure, thanks for all the information.

**Comment by probonopd** [comment] 2018-07-14 03:59
> I think that the defunct process comes from this fork().
> 
> I wonder if the fix is as simple as adding waitpid(pid, NULL, 0) here, making AppImage explicitly responsible for reaping its own child.

Let's try it then.

> (I confess I'm confused about what the keepalive pipe is doing in that code!)

It is meant to keep the mounted FUSE running until all child processes have exited. Did I do it wrong?

**Comment by dimbleby** [comment] 2018-07-14 12:14
Well I was running out of enthusiasm last night but this morning I decided that I might as well see this through - and I'm delighted to report that the proposed fix does indeed produce an appimage that works well even with 'bad' vim.

So I guess this was an appimage bug all along!  (Though I'm also happy to report that neovim has accepted my pull request making them more resilient to it).

Pull request coming shortly.

**Comment by TheAssassin** [comment] 2018-07-14 12:16
Heh, well, let's say both nvim and AppImageKit had their bugs. Thanks for the PR, I'll merge it after some testing.

**Closed** 2018-07-14 12:44 UTC
Labels: bug, deprioritized, pr-welcome

**Comment by probonopd** [comment] 2018-07-15 13:03
Thank you very much. Glad the solution was just one line.
