### ISSUE TITLE
Specifying default runtime with appimagetoolkit causes error with appimaged

### ISSUE THREAD

**Issue by JoshuaD84** [AppImage/AppImageKit#521] opened 2017-11-12 16:51 UTC
On a 64 bit system I ran:

`./appimagetool-x86_64.AppImage --runtime-file runtime-x86_64 Output.AppImage`

The appimage works fine. However, when appimaged comes across it, I get this error:

> Blindly assuming AppImage type 1
> The author of this AppImage should embed the magic bytes, see https://github.com/AppImage/AppImageSpec
> -> REGISTER ~/bin/Output.AppImage
> ISO9660 based type 1 AppImage
> Unrecognized archive formatUnrecognized archive format

When I removed the argument `--runtime-file runtime-x86_64` the problem in appimaged went away. 

AppImageTool version:

> $ ./appimagetool-x86_64.AppImage --version                                                         
> Version: continuous-6-g58522bd

I cannot find the version number of the runtimes, but they were downloaded on October 29th and I believe they are the most recent versions.

**Comment by TheAssassin** [comment] 2017-11-12 16:54
The "most recent" ones are the `continuous` builds which are built every day. See https://github.com/AppImage/AppImageKit/releases/tag/continuous. Also, we recently released version 10, which can be found here: https://github.com/AppImage/AppImageKit/releases/tag/10

Please try with version 10, and see if it works.

**Comment by TheAssassin** [comment] 2017-11-12 17:21
@JoshuaD84 if you can provide a sample, I'll check it by hand and we'll see what kind of bug you're hitting (might be some problem in the byte order etc.).

**Comment by JoshuaD84** [comment] 2017-11-12 20:05
http://hypnosplayer.org/download/beta1/Hypnos-with-error.AppImage

**Comment by probonopd** [comment] 2017-11-12 20:20
```
me@host:~$ ./Hypnos-with-error.AppImage --appimage-version
Version: continuous-6-g58522bd
```

So that is correct...

**Comment by probonopd** [comment] 2017-11-12 20:58
The magic bytes _should_ be injected here but apparently this is not working out:

https://github.com/AppImage/AppImageKit/blob/4a727a0c14f1a55b3f0d9a675d2d9717f48d34ba/build.sh#L215-L217

**Comment by TheAssassin** [comment] 2017-11-12 21:18
```
> xxd Hypnos-with-error.AppImage | head -n3
00000000: 7f45 4c46 0201 0100 0000 0000 0000 0000  .ELF............
00000010: 0200 3e00 0100 0000 2821 4000 0000 0000  ..>.....(!@.....
00000020: 4000 0000 0000 0000 b873 0100 0000 0000  @........s......
```

I can't see the magic bytes in there:

```

**Comment by TheAssassin** [comment] 2017-11-12 21:24
```
> xxd runtime-x86_64  | head -n1
00000000: 7f45 4c46 0201 0100 0000 0000 0000 0000  .ELF............
```

That's the exact same line as with the broken AppImage. Therefore it is confirmed that the published runtimes are broken already.

**Comment by probonopd** [comment] 2017-11-16 18:03
Maybe also causing to https://github.com/AppImage/appimage.github.io/issues/135?

**Comment by probonopd** [comment] 2017-11-18 10:54
In
https://travis-ci.org/AppImage/AppImageKit/jobs/303224191#L7128
it is still correct, whereas in
https://travis-ci.org/AppImage/AppImageKit/jobs/303224191#L8105
it is broken.

What is happening in the meantime that destroys the magic bytes?

**Comment by probonopd** [comment] 2017-11-18 15:05
Fixed in 031365d - turns out running `strip` on the runtime removes the magic bytes. @develar @JoshuaD84 please retry with the latest continuous build.

**Comment by probonopd** [comment] 2017-11-18 15:08
Maybe we should file a bug for `strip`, although that will not help our build system until that fix has arrived in the oldest still-supported LTS, which will take half a decade. https://sourceware.org/bugzilla/buglist.cgi?quicksearch=strip

**Comment by TheAssassin** [comment] 2017-11-18 15:12
@probonopd we can always ship our own dev tools.

**Comment by probonopd** [comment] 2017-11-18 15:24
The issue is more that when someone (not us) runs the stock `strip`, then the magic bytes get removed.

**Comment by TheAssassin** [comment] 2017-11-18 15:48
That's a layer-8 problem in my opinion. We might be able to test for that however: call strip, check whether magic bytes are contained, if they're not, show warning and use non-stripped version.

**Comment by TheAssassin** [comment] 2018-07-10 11:11
I think we can close this as resolved. Please reopen if you think otherwise.

**Closed by TheAssassin** 2018-07-10 11:11 UTC
Labels: bug, high-priority
