### ISSUE TITLE
cannot build sample AppImage with osc on ubuntu 16.04

### ISSUE THREAD

**Issue by slowphil** [AppImage/AppImageKit#607] opened 2018-01-03 21:54 UTC
when trying "osc build AppImage x86_64 appimage.yml" on home:probono/QtQuickApp I get the following error:
```
...
[    3s] now finalizing build dir...
[    3s] cp: omitting directory '/home/phil/home:probono/QtQuickApp/QtQuickApp'
[    3s] Unpacking QtQuickApp.obscpio ...
[    3s] 72 blocks
[    3s] Running build time source services...
[    3s] -----------------------------------------------------------------
[    3s] ----- building appimage.yml (user abuild)
[    3s] -----------------------------------------------------------------
[    3s] -----------------------------------------------------------------
[    3s] bash: dpkg-architecture: command not found
[    3s] 
[    3s] mylinuxpc failed "build appimage.yml" at Wed Jan  3 21:33:56 UTC 2018

```
Note that my system does have dpkg-architecture installed. 
I also tried running the osc AppImage (instead of the one taken from OBS) and it immediatly fails with :
`ImportError: No module named site`

What distro are you normally using for running osc ?

**Comment by TheAssassin** [comment] 2018-01-03 21:58
First of all, we are not responsible for OpenSUSE build service, and we did not develop the integration. I have a few ideas, but I will close the issue, you will have to ask the OpenSUSE team.

As far as I know, `osc` doesn't build on the host system, but sets up an isolated environment (I think it was a chroot). So, maybe update your osc? There's regular changes in their system, and the server side and client side components should be in sync.

**Closed by TheAssassin** 2018-01-03 21:58 UTC

**Comment by slowphil** [comment] 2018-01-03 22:50
I understand you are not making osc and cannot fix the issue on your own. However, why closing the issue? Isn't it important and relevant to document _here_ that this way of making AppImages may not work as advertized on [your own wiki](https://github.com/AppImage/AppImageKit/wiki/Using-Open-Build-Service)?

Also the same wiki says 

>  In case you encounter problems, please report an issue, and we'll try to verify and fix it.

Shall I understand that in that this sentence was a quotation from an OpenSuse guy? In that case please clarify the wiki, specifying were to report issues when trying to build AppImages as described in the wiki.

FYI [I have also reported the issue at OBS](https://github.com/openSUSE/osc/issues/365)

**Comment by probonopd** [comment] 2018-01-03 22:53
I am not sure whether the OBS-provided AppImage-related tools are even _supposed_ to be run on deb-based distributions, since as far as I know all OBS-produced AppImages are produced on rpm-based openSUSE systems. Maybe @adrianschroeter can give a definitive answer here. Thanks.

**Comment by TheAssassin** [comment] 2018-01-03 23:04
@slowphil the issue is documented in the other issue, to be fair. Also, the builds work on OBS, which is what we're involved in. `osc build` and the online system just differ too much. I haven't ever used `osc build`, I rather push my changes and have the server build it for those reasons. I did consider moving this to the OBS repo to be the best possibility.
