### ISSUE TITLE
[Feature] OpenBSD Port

### ISSUE THREAD

**Issue by ghbjklhv** [AppImage/AppImageKit#961] opened 2019-05-20 02:52 UTC
**Description** I would like to discuss the possibility of Appimages possibly being extended to work on OpenBSD. As well as implementing Appimages to run on OpenBSD and forks like LibertyBSD.

Related to #98 , which has became more about a FreeBSD implementation.
_____________________

Want to support this issue? Post a [bounty on it](https://www.bountysource.com)! We accept bounties via [BountySource](https://www.wikipedia.org/wiki/Bountysource).

**Comment by probonopd** [comment] 2019-05-20 06:14
See if you can compile `runtime.c`, if yes the it might be possible.

**Comment by TheAssassin** [comment] 2019-05-20 11:33
Duplicate of #98.

**Closed by TheAssassin** 2019-05-20 11:33 UTC

**Comment by ghbjklhv** [comment] 2019-05-24 23:30
@TheAssassin Aye, could you reopen this issue?
#98 has become more about FreeBSD, the most popular of the BSDs.

However, it has many differences to OpenBSD. 
Therefore, I believe it is necessary to start a new discussion thread.

**Comment by TheAssassin** [comment] 2019-05-24 23:47
Can you give an example on how they're different so that it'd affect the development of BSD compatibility? AFAICS the differences are more about details in user space, not about the basic OS functionality?

**Comment by probonopd** [comment] 2019-05-25 06:02
The point is, no one is working on this for _any_ BSD, so we don't need to open a ticket for _every_ BSD.
