### ISSUE TITLE
[32-bit] appimagetool names architecture wrongly

### ISSUE THREAD

**Issue by probonopd** [AppImage/AppImageKit#312] opened 2016-12-03 19:49 UTC
We want `i686` as part of the filename for [32-bit](https://github.com/probonopd/AppImageKit/pull/307) Intel AppImages, but `appimagetool` names them `appname-version-Intel_80386.AppImage`. This is on Ubuntu 16.04.

**Comment by marguerite** [comment] 2016-12-20 14:58
same here, on openSUSE Tumbleweed

**Comment by LeCharlatan** [comment] 2017-02-15 21:42
Same here *Intel_80386.AppImage
Kubuntu Xenial

**Comment by probonopd** [comment] 2017-02-15 21:55
Should be an easy "replace string" type of fix - any volunteers for a Pull Request?

**Comment by Sod-Almighty** [comment] 2017-04-13 19:31
I'll have a go

**Comment by Sod-Almighty** [comment] 2017-04-13 22:00
I have a question. Have you guys ever heard of something called a "memory leak"? Because there are precisely zero `free()` calls in `appimagetool.c`...

**Comment by Sod-Almighty** [comment] 2017-04-14 01:19
I've coded a fix for this, but can't test it because `build.sh` fails on Debian. I also can't issue a pull request because my previous pull hasn't yet been accepted.

**Comment by TheAssassin** [comment] 2017-04-14 08:38
> I have a question. Have you guys ever heard of something called a "memory leak"? Because there are precisely zero free() calls in appimagetool.c...

So what? How experienced are you with C? You don't need `free()` at all in C, unless you perform manual memory management (e.g. with `malloc()`).

>I've coded a fix for this, but can't test it because build.sh fails on Debian.

Without the error log, we won't be able to help you at all. "It fails" is like ["works on my machine"](https://blog.codinghorror.com/the-works-on-my-machine-certification-program/).

> I also can't issue a pull request because my previous pull hasn't yet been accepted.

That's not true. The problem is that you sent your pull request from your master branch. But even GitHub themselves tell you not to do so, but to [use a feature branch](https://help.github.com/articles/about-pull-requests/).

To solve the problem, you need a clean new branch that you can work on. First, get familiar with the branch concept. The git book has a [chapter](https://git-scm.com/book/en/v2/Git-Branching-Branches-in-a-Nutshell) about that.

These commands are going to create such a clean new branch. On your workstation, run:

```
# add original repository as a so-called git remote to be able to check out a clean copy of the branch
git remote add upstream https://github.com/probonopd/AppImageKit.git

# now check out a topic branch from the upstream master branch, if you omit the above step, your own master branch is used, and thus the commits that are currently awaiting a merge are in the new PR, too
git checkout -b mygithubusername/feature-patch-whatever-123 upstream/master
```

Now you are on that new branch `mygithubusername/feature-patch-whatever-123`. Start working and committing.
When you try to push it to your repository, use `git push --set-upstream origin mygithubusername/feature-patch-whatever-123`. GitHub will help you create a PR on the website from then on.

**Comment by Sod-Almighty** [comment] 2017-04-14 13:24
> How experienced are you with C? You don't need free() at all in C, unless you perform manual memory management (e.g. with malloc()).

I've never liked C much, but I've had a decent amount of experience with it.

On line 339, you check that `arch` is null. Then, on line 361 –
```
arch = g_strstrip(g_strsplit_set(line, ",", -1)[1]);
```
– after which you proceed to use it. Now, I checked the documentation for `g_strstrip`, but it wasn't clear. Either way, however, there are only two possibilities. Either it's allocated a new string on the heap, in which case you're failing to `free()` it, or it's merely indexing into the existing string `line`. Unfortunately, `line` goes out of scope at line 371, and you're still using `arch` as late as line 515.

(Given the intended behaviour of `g_strstrip`, it's unlikely to be the second option.)

In summary, either you have a memory leak or a dangling pointer. Am I mistaken?

> Without the error log, we won't be able to help you at all.

I understand this. But I already [submitted an error log](https://github.com/probonopd/AppImageKit/issues/376#issuecomment-292745141) (which **probonopd** subsequently edited and truncated, as it happens).

Oddly, I just ran `build.sh` again to generate a new error log for you, and....it worked. Perhaps it's been fixed since I last ran it? Anyhow, it's working for the moment. If I have further problems, I'll submit a new error log.

> The problem is that you sent your pull request from your master branch ... get familiar with the branch concept. The git book has a chapter about that.

Yes, I am sadly very ignorant of git. I feel very much out of my depth with it all. I'm an experienced programmer in several languages, but git is not something I have really used. Thanks for the link - I will look into it.

---

On the subject of git...my own program code tends to be in two parts. Each project has a bunch of its own code, obviously, but much of my code is shared between all of them. So my directory structure tends to be kinda like this:

- project1/
- project2/
- shared-code/

I've never understood how git (or another version control system) could be used in this situation, which is why I've never really used it. The projects each have a dependancy upon `shared-code`, but they don't own it. What's the correct way to deal with this?

**Comment by TheAssassin** [comment] 2017-04-14 13:39
The git discussion is actually off-topic, I just tried to give you a few pointers how to use it to contribute more efficiently, but we should stop this discussion in this issue thread.
However, I am willing to discuss this kind of stuff on IRC with you. Join again and ask a few questions.

**Comment by TheAssassin** [comment] 2017-04-14 20:48
> Either it's allocated a new string on the heap, in which case you're failing to free() it, or it's merely indexing into the existing string line. Unfortunately, line goes out of scope at line 371, and you're still using arch as late as line 515.

Right, I see what you mean... [the docs](https://developer.gnome.org/glib/stable/glib-String-Utility-Functions.html#g-strstrip) say it returned a string, so I assume it is a pointer to some heap memory. But the variable `arch` itself doesn't go out of scope until 654, as the variable is created in 316. What goes out of scope is the assignment, but that doesn't have an influence on the variable scope.
I guess it should really be freed, but even if it isn't freed, the code is just run once, so it is not (yet) a memory leak but just some memory overhead. It would become a problem as soon as these lines of code would be run more than once.
Though, it should be fixed. Feel free to send a PR. If you can spot more of these, they should be fixed, too, of course.

**Comment by Sod-Almighty** [comment] 2017-04-15 02:36
Sure, I'll work on it as soon as I get enough of a handle on git to put such fixes in their own branches. As I say, I'm massively ignorant of git.

**Comment by kyodev** [comment] 2017-07-05 18:20
on Debian 9, Stretch: KeePassXC-*-Intel_80386.AppImage

one suggestion:
in according with this [PR](https://github.com/keepassxreboot/keepassxc/pull/737), why not use the same commands?

I never used the language C then I can't make a PR, but if you can inspire of this code:
```C
        /* Determine the architecture */
        gchar *arch = getenv("ARCH");
        /* If no $ARCH variable is set check with commands */
        if (!arch) {
            /* display: x86_64 for 64bits, i686 for 32bits */
            sprintf (command, "uname -m", arch);
            if(!arch)
            {
                /* display: 64 for 64bits, 32 for 32bits */
                gchar *archlb = NULL;
                sprintf (command, "getconf LONG_BIT", archlb);
                if (archlb == "32") arch = "i686";
                else if (archlb == "64") arch = "x86_64";
            }
            if(!arch)
            {
                printf("The architecture could not be determined, assuming 'all'\n");
                arch="all";
            }
        }
```
```
--- appimagetool.ini.c	2017-07-05 18:58:56.522149087 +0200
+++ appimagetool.c	2017-07-05 20:12:16.159439417 +0200
@@ -383,31 +383,14 @@
 ```
**warning** I don't know really if it work :(

**Closed** 2018-11-05 15:17 UTC
Labels: bug
