### ISSUE TITLE
Apprun and .DirIcon not generated by AppDirAssistant

### ISSUE THREAD

**Issue by ghost** [AppImage/AppImageKit#10] opened 2014-05-14 09:43 UTC
I'm trying to create appimages of [Pale Moon for Linux](http://pm4linux.sf.net/) on Xubuntu 14.04. AppDirAssistant correctly detects the files and folders installed, but does not create an Apprun and the .DirIcon file.

Latest released versions (available on portablelinuxapps.org) have been used for this purpose.

```
$ ./AppDirAssistant
[xcb] Unknown sequence number while processing queue
[xcb] Most likely this is a multi-threaded client and XInitThreads has not been called
[xcb] Aborting, sorry about that.
python: ../../src/xcb_io.c:274: poll_for_event: Assertion `!xcb_xlib_threads_sequence_lost' failed.
0
[<class '__main__.WelcomePage'>, 'Welcome']
Preparing <WelcomePage 'Welcome'>
Preparing <TooNewPage 'Warning'>
Preparing <InstallNowPage 'Install your application now'>
Preparing <ProfilerPage 'Profiling...'>
```

**Comment by probonopd** [comment] 2015-01-05 18:28
Cannot reproduce

**Comment by probonopd** [comment] 2015-08-11 08:38
Can reproduce on Xubuntu 15.10 (Wily Werewolf) development branch. After installing python, the following happens:

```
me@host:~$ '/home/me/Downloads/AppDirAssistant 0.3.3-64bit'
49
[<class '__main__.WelcomePage'>, 'Welcome']
Preparing <WelcomePage 'Welcome'>
Preparing <TooNewPage 'Warning'>
Preparing <InstallNowPage 'Install your application now'>
Preparing <ProfilerPage 'Profiling...'>
['/tmp/.mount_LA8Sq7/usr/bin/profileapp.py', '/home/me/Desktop/Googleplaydownloader.AppDir', 'googleplaydownloader']
appimager: Fatal IO error 11 (Resource temporarily unavailable) on X server :0.0.
```
In this case, AppDirAssistant is killed prematurely and AppRun is not created.

**Comment by TheAssassin** [comment] 2017-06-05 16:08
At a glance it looks like these issues were about AppImage type 1. This type is no longer developed and we do not recommend using it any more.

I think I can safely close this issue.

**Closed by TheAssassin** 2017-06-05 16:08 UTC
Labels: bug

**Comment by probonopd** [comment] 2017-06-05 16:16
AppDirAssistant and AppImageAssistant are deprecated.
