### ISSUE TITLE
AppImageKit is broken when using system XZ

### ISSUE THREAD

**Issue by nurupo** [AppImage/AppImageKit#787] opened 2018-05-22 11:24 UTC
AppImageKit's cmake expects the `xz_LIBRARIES` to contain `liblzma.a`, it even builds the xz with `--disable-shared --enable-static`, but when using system XZ (at least on Debian and Ubuntu), both `liblzma.a` and `liblzma.so` are present on the system and cmake sets `xz_LIBRARIES` to `liblzma.so`. `xz_LIBRARIES` being set to `liblzma.so` breaks things, as AppImageKit, expecting it to be `liblzma.a`, asks the linked to link it statically with `-Wl,-Bstatic "@xz_LIBRARIES@"` in a couple of places, including `cmake/dependencies.cmake` and `src/build-runtime.sh.in`, which causes the following error:

>/usr/lib/gcc-cross/arm-linux-gnueabi/6/../../../../arm-linux-gnueabi/bin/ld: attempted static link of dynamic object `/usr/lib/arm-linux-gnueabi/liblzma.so

Weirdly enough, `x86_64-linux-gnu` and `i386-linux-gnu` toolchains will happily do `-Wl,-Bstatic "liblzma.so"` without an error, but `arm-linux-gnueabi` and other will error. Well, the error is expected, you should not statically link shared libraries, that should have been `liblzma.a` instead of `liblzma.so`.

As far as I know, there is no clear way to ask `find_package()` to find a static library instead of a shared one. cmake's PkgConfig module, however, [does allow to get shared and static separately](https://cmake.org/cmake/help/v3.7/module/FindPkgConfig.html) (the `<PREFIX>_STAITC` part).

**Comment by TheAssassin** [comment] 2018-05-22 13:03
Looks like you're right. We can of course switch to using pkg-config for this dependency. Do you want to send a PR fixing the issue?

**Comment by TheAssassin** [comment] 2018-07-17 01:51
I looked into pkg-config as an alternative to `find_library` while working on #789, and I reworked my own `pkg-config` related functions to even support the static linking part. The problem is that the `liblzma` pkg-config file doesn't properly declare the static linking, therefore even using `--static`/`_STATIC` will cause CMake to link to the shared object.

If we want to link to the system wide installed archive, we will have to use `find_library` completely ourselves, not via `FindLibLZMA.cmake` etc. That's quite annoying, actually, because I invested quite some time into the pkg-config related code to support static linkage.

I do want to get rid of as many external dependencies we build ourselves at the moment as possible, and stuff like `liblzma` that is almost never updated can be used safely from the system in most cases, I'd say.

I think what I'm going to do is create some function to import the system wide installed archives.

**Comment by nurupo** [comment] 2018-07-18 06:22
How about this? Name it `FindLibLZMAStatic.cmake`. It looks specifically for static library filenames `lzma.a` or `liblzma.a`, so it will pick up only the static library.

```cmake
# - Try to find static liblzma
# Once done, this will define
#
#  LIBLZMA_STATIC_FOUND - system has static liblzma
#  LIBLZMA_STATIC_INCLUDE_DIRS - the liblzma include directories
#  LIBLZMA_STATIC_LIBRARIES - link these to use liblzma

include(LibFindMacros)

# Use pkg-config to get hints about paths
libfind_pkg_check_modules(LIBLZMA_STATIC_PKGCONF LIBLZMA)

find_path(LIBLZMA_STATIC_INCLUDE_DIR
  NAMES lzma.h
  PATHS ${LIBLZMA_STATIC_PKGCONF_INCLUDE_DIRS}
)

find_library(LIBLZMA_STATIC_LIBRARY
  NAMES lzma.a liblzma.a
  PATHS ${LIBLZMA_STATIC_PKGCONF_LIBRARY_DIRS}
)

set(LIBLZMA_STATIC_PROCESS_INCLUDES LIBLZMA_STATIC_INCLUDE_DIR)
set(LIBLZMA_STATIC_PROCESS_LIBS LIBLZMA_STATIC_LIBRARY)
libfind_process(LIBLZMA_STATIC)
```

**Comment by nurupo** [comment] 2018-07-18 06:38
Hm, ignore that, I was following [this wiki](https://gitlab.kitware.com/cmake/community/wikis/doc/tutorials/How-To-Find-Libraries) and apparently LibFindMacros.cmake is not included into the default cmake distribution.

**Comment by nurupo** [comment] 2018-07-18 06:46
This would work then

```cmake
# - Try to find static liblzma
# Once done, this will define
#
#  LIBLZMA_STATIC_FOUND - system has static liblzma
#  LIBLZMA_STATIC_INCLUDE_DIRS - the liblzma include directories
#  LIBLZMA_STATIC_LIBRARIES - link these to use liblzma

find_package(PkgConfig)
pkg_check_modules(PC_LIBLZMA QUIET liblzma)

find_path(LIBLZMA_STATIC_INCLUDE_DIR
  NAMES lzma.h
  HINTS ${PC_LIBLZMA_INCLUDEDIR} ${PC_LIBLZMA_INCLUDE_DIRS}
)

find_library(LIBLZMA_STATIC_LIBRARY
  NAMES lzma.a liblzma.a
  HINTS ${PC_LIBLZMA_LIBDIR} ${PC_LIBLZMA_LIBRARY_DIRS}
)

include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(LIBLZMA_STATIC DEFAULT_MSG LIBLZMA_STATIC_INCLUDE_DIR LIBLZMA_STATIC_LIBRARY)

mark_as_advanced(LIBLZMA_STATIC_INCLUDE_DIR LIBLZMA_STATIC_LIBRARY)

set(LIBLZMA_STATIC_LIBRARIES ${LIBLZMA_STATIC_LIBRARY})
set(LIBLZMA_STATIC_INCLUDE_DIRS ${LIBLZMA_STATIC_INCLUDE_DIR})
```

**Comment by TheAssassin** [comment] 2018-07-18 15:08
Initially I wanted to add some reusable function to `dependencies.cmake` that imports the static libraries, similar to what you did, but without using FPHSA. Are you okay if I take your code and transform it into such a function?

**Comment by nurupo** [comment] 2018-07-18 20:00
Sure, use it whichever you like.

**Comment by TheAssassin** [comment] 2018-07-23 00:32
Closing this issue as wontfix. When building against the system libraries, we assume the user wants to build binaries that are only of use on that target system, e.g., libappimage for use with other software projects. It wouldn't be useful and probably not even permitted to link the system dependencies statically.

If static linking is required, one has to build the libraries the way we want them to do. This ensures that the binaries they build work on other systems, too.

**Closed by TheAssassin** 2018-07-23 00:32 UTC
Labels: wontfix

**Comment by nurupo** [comment] 2018-07-23 01:40
Huh, so you need to build the static XZ in some special way otherwise it won't work on other systems? Alright, if that's so then it makes sense.

**Comment by TheAssassin** [comment] 2018-07-23 16:16
No, but I don't want to add even _more_ complexity to the build scripts. Linking to shared libs is a valid use case, and even necessary when packaging for distributions.
