### ISSUE TITLE
appimagetool fails because of an outdated desktop-file-validate

### ISSUE THREAD

**Issue by txtsd** [AppImage/AppImageKit#1171] opened 2022-02-07 02:32 UTC
[Link to GitHub Actions log](https://github.com/txtsd/PolyMC/runs/5084594197?check_suite_focus=true#step:14:8207)

```
[appimage/stdout] /home/runner/work/PolyMC/PolyMC/install/org.polymc.polymc.desktop: error: file contains key "PrefersNonDefaultGPU" in group "Desktop Entry", but keys extending the format should start with "X-"
```

But `PrefersNonDefaultGPU` IS a valid key in the [Desktop Entry Spec](https://specifications.freedesktop.org/desktop-entry-spec/desktop-entry-spec-latest.html#recognized-keys).

And if I update the `Version` key in the file to the current `1.5`
It fails with:
```
[appimage/stdout] /home/runner/work/PolyMC/PolyMC/install/org.polymc.polymc.desktop: error: value "1.5" for key "Version" in group "Desktop Entry" is not a known version
```

Please update the included `desktop-file-validate`.

**Comment by TheAssassin** [comment] 2022-02-07 18:01
Yes, we can. All known implementations do not hard-fail if there are unknown keys, and they don't check the version marker. Everything else would be pretty pointless. They're both forward as well as backward compatible.

**Comment by probonopd** [comment] 2022-02-07 18:14
> Yes, we can.

Do what?

**Comment by probonopd** [comment] 2022-02-07 18:23
__If__ we can be reasonably sure that

> They're both forward as well as backward compatible

is true for all implementations of the XDG Desktop spec. Isn't that a BIG "if"?

**Comment by TheAssassin** [comment] 2022-02-07 18:29
Let's say I haven't seen any of these in all my time spent on various distros. There's also much worse issues which appimagetool doesn't account for, e.g., icon theme issues (appimagelint does implement these checks for instance). As said, any such limitation makes no sense technically (it is safe to ignore all broken/unknown values, these files do not contain anything relevant security wise) and UX wise (I'm sure users would be annoyed if an app was entirely missing in their menu just because of a typo in some icon or a category).

You already implemented one extra requirement (categories) on top of `desktop-file-validate`, which again is more a "bad style" issue rather than a technical one (the application can be displayed, but it will be shown in some "other" category) and should thus lead to warnings but not make appimagetool hard-fail. As said, when checks seem too aggressive or even unnecessary, they'll rather be patched out, leading to more issues.

Let me ask you this question: Why in the world limit yourself to `1.0` even? Are you sure even the oldest distro can't use a later version? At the moment, this requirement you just named seems completely arbitrary.

**Comment by probonopd** [comment] 2022-02-07 18:35
> Are you sure even the oldest distro can't use a later version?

I haven't checked. But my blind assumption there was that every distro _at least_ supports 1.0, because all specs before that were not _stable_ anyway.

This is how I generally operate - assume the lowest common denominator you are aware of. Never just assume that something newer can be taken for granted, unless you have checked that it actually can.

**Comment by probonopd** [comment] 2022-02-07 18:38
@txtsd what makes you think that `Version=1.5` is supported by _all still supported Linux distributions_? Did you do any research in that direction? (I'd like to understand why you gave me a :-1:  on my answer.)

**Comment by TheAssassin** [comment] 2022-02-07 18:49
Just build it the tool yourself, that's done with tons of other stuff already in this and other repositories, too. No reason to wait for some binary to fall into your lap. The code base is really small, https://gitlab.freedesktop.org/xdg/desktop-file-utils. It won't take very long.

Specifications like the ones from freedesktop are really really generous regarding compatibility. Just look at `Type` on https://specifications.freedesktop.org/desktop-entry-spec/latest/ar01s06.html. The majority of keys is even optional. Again, technically there is no reason to not just ignore unknown keys. Even a newbie would do that. Anything else is bad UX. Implementations follow that same approach. Look at icons for instance, it's best practice to put them into `/usr/share/applications/<theme>/<resolution>/apps`, but I bet you that most implementations won't mind if you forget the `apps` bit...

Now if you really want to discuss speculations, let me answer a few of yours, too:

> because all specs before that were not stable anyway.

You just assume `1.0` was a stable release, everything else was "unstable" (whatever that means, though). That only works in semver, and only if people strictly adhere to that. There's plenty tools that have never reached a `1.0`, the same goes for specifications. I'd call that pure speculation on your end.

> is true for all implementations of the XDG Desktop spec. Isn't that a BIG "if"?

I gave a well reasoned explanation why it makes sense to assume both forward _and_ backward compatibility. That's more of an educated guess than speculation. Of course, nobody can give you a definite answer for *all* the implementations of those specs, because nobody can enumerate them. But nobody cares about the 0.005%, really. It's a *tiny* if at most. I still doubt there exists even one implementation which would hard-fail on unknown keys.

It makes sense for a linter to complain about broken or invalid values. But that doesn't mean that incorrect values will lead to incorrect behavior. Look at `shellcheck` for instance, it'll complain about tons of bad shell code, however something like `exit $(echo 0)` will just work even though escaping is missing. You must take into account the context.

> all still supported Linux distributions

That requirement is completely made up. For a majority of AppImage creators, the oldest still-supported LTS of Ubuntu/Debian is a more suitable target. They don't even _want_ to support ancient Linux. This is arbitrary paternalism. Not even the AppImage spec requires any of this.

**Comment by txtsd** [comment] 2022-02-07 18:51
@probonopd No idea why you're building an argument off an assumption.

I thumbed you down because of this:
> Removing the Version key altogether in the desktop file is usually the easiest solution.

which is a hacky workaround, to an easy solution which you're over-complicating.

I've never seen a desktop-file based error because of a key that wasn't supported. Not once.

Lots of people use AppImages to build and ship software with latest versions of libraries which are otherwise not supported on older distros. I'm not sure why `desktop-file-validate` has to support the ONLY oldest Desktop Entry spec, and you insist on it hard-failing instead of just spitting out a warning.

**Comment by TheAssassin** [comment] 2022-02-07 19:10
The specification reiterates that both forward and backward compatibility should be ensured in various places. I just found another one:

> Interface definers should take care to keep issues of backward and forward compatibility in mind when designing their interfaces.
> -- https://specifications.freedesktop.org/desktop-entry-spec/desktop-entry-spec-latest.html#interfaces

You even mentioned yourself that if `Version` is not included at all, it'll just work. Exactly, that's the point. I already mentioned that all the implementations I am aware of don't even check that key, but ignore it.

I'd even question whether it's the correct behavior of `desktop-file-validate` to start complaining when a desktop entry contains `Version=1.5`, which is newer than what it understands. But I'd question a lot of its behavior. Again, there's no point in making things which clearly don't break errors, they should at most be warnings.

Random example from some KDE log:

```
Unknown key name 'TerminalOptions' in section 'Desktop Entry', ignoring.
```

**Comment by probonopd** [comment] 2022-02-07 19:10
> Just build it the tool yourself, that's done with tons of other stuff already in this and other repositories, too. 

Been there, done that. Building static binaries even:
https://github.com/probonopd/static-tools

Currently I use this for https://github.com/probonopd/go-appimage/.

> Specifications like the ones from freedesktop are really really generous regarding compatibility

> I've never seen a desktop-file based error because of a key that wasn't supported. Not once.

I trust your collective judgement here.

> I thumbed you down because of this

Thanks for the explanation. I was thinking "removing the Version key altogether _and using only keys that were specified in 1.0_ ".

**Comment by Tachi107** [comment] 2022-04-29 10:27
For some users being able to use `PrefersNonDefaultGPU` is more important than supporting hypothetical distros that would refuse to open .desktop files that target version 1.5 of the spec. 

@probonopd, could you please consider throwing a warning instead of a hard error?

**Comment by probonopd** [comment] 2022-04-29 18:11
> hypothetical distros that would refuse to open .desktop files that target version 1.5 of the spec

A hypothetical bug should be filed against hypothetical distros which don't open 1.0 desktop files.

**Comment by Tachi107** [comment] 2022-04-29 18:21
> A hypothetical bug should be filed against hypothetical distros which don't open 1.0 desktop files.

I don't understand... Why was this closed? As @TheAssassin said, unknown keys are supposed to be ignored by old distros that don't support version 1.5 of the spec, so it shouldn't be an issue for AppImage apps to ship those.

If you could point me to the list of currently supported distros I'll be happy to check if this is actually the case. All I can say right now is that if you add an invalid key in .desktop files it is ignored by my DE (Xfce), gtk-launch and xdg-open, so this is probably what would happen in older versions as well.

**Comment by Tachi107** [comment] 2022-04-29 18:31
> @probonopd A hypothetical bug should be filed against hypothetical distros which don't open 1.0 desktop files.

To be clear, the issue is not that distros can't open 1.0 .desktop files, but that AppImageTool refuses to accept non-1.0 .desktop files while all distros (new and old) are able to process them just fine, as long as the required keywords are present - i.e. AppImage is imposing an unnecessary restriction that limits what users are able to ship

**Comment by probonopd** [comment] 2022-04-29 18:33
We are using version 1.0 of the spec, not version 1.5.

**Comment by Tachi107** [comment] 2022-04-29 18:35
> We are using version 1.0 of the spec, not version 1.5.

I understand this, but why is this necessary? I might be looking at the issue from the wrong prospective, so please bear with me :)

**Comment by probonopd** [comment] 2022-04-29 18:36
We dislike the overcomplicated XDG specs. So we want to support just the very bare minimum that is absolutely required.

**Comment by Tachi107** [comment] 2022-04-29 18:45
> I like "software minimalism" an hence dislike the overcomplicated XDG specs, so my tools support just the very bare minimum of XDG that is absolutely required.

I agree with you here, but it is also true that AppImages don't need to support the key themselves; it's up to the distro itself (for example, I believe that even the latest Xfce release, while it might support new versions of the XDG specs it doesn't seem support this particular key, and that's completely fine as it is just a "preference" that the app has)

> Besides, any change in our codebase is work that someone has to do: Make a change, test the change, etc.

I know it well, and contributors can really help

> If someone comes up with a pull request and can proof that it breaks nothing, then it may be considered.

I might look into this soon.

> Including a new version of `desktop-file-validate` that is more permissive when it comes to unknown keys that runs on old, REALLY old, target systems. But really, we don't want this stuff to change all the time.

The change shouldn't break compatibility with supported targets, there's no question about that

> Personally, I don't like "moving targets". So I usually take a version of something that works for me and continue to use that forever. Unless there is really a _need_ for something newer.

Well, this key solves a real issue that improves the experience for a lot laptop users, and improving the experience of the linux desktop is always a good thing

**Comment by probonopd** [comment] 2022-04-29 19:33
> The change shouldn't break compatibility with supported targets, there's no question about that

What I meant is:
If you want a newer `desktop-file-validate` to be bundled, then you need to make sure that such a version of `desktop-file-validate` will still be able to run on all the distribution versions which our old `desktop-file-validate` could run on.

**Comment by probonopd** [comment] 2022-04-29 19:34
Like these:
https://github.com/probonopd/static-tools/releases

(Look at how they were made)

**Comment by Tachi107** [comment] 2022-04-29 19:35
> Like these: https://github.com/probonopd/static-tools/releases
> 
> (Look at how they were made)

Thanks, I'll take a look now

**Comment by Pointedstick** [comment] 2022-06-16 17:51
See https://github.com/endless-sky/endless-sky/pull/6923 for an example of a specific, real-world use case that is being hampered by the decision to not either update `desktop-file-utils` or else at least patch it to accept the version 1.5 keys.

**Comment by probonopd** [comment] 2022-06-20 18:25
Maybe the right thing to do would be for `desktop-file-validate` to allow (but inform about) unknown keys.

In the meantime, all we need to do is to remove the "offending" `desktop-file-validate` and replace it with a newer (statically linked) version.

This copies `desktop-file-validate` into the AppDir:

https://github.com/AppImage/AppImageKit/blob/1f739c1bea7e0b8bb91c66011492515acb3ae9fc/ci/build-appdir.sh#L44-L47

So it seems to me that we "just" need to put a newer version of `desktop-file-validate` into `/deps/bin` on the build system.

I would add

```
if [ ! -f /deps/bin/desktop-file-validate ] ; then
  mkdir /deps/bin
  wget https://github.com/probonopd/static-tools/releases/download/continuous/desktop-file- validate-x86_64 -O /deps/bin/desktop-file-validate
  chmod +x /deps/bin/desktop-file-validate
fi
```

before line 44 but I have the suspicion that @TheAssassin would like to see it done differently...

**Comment by Pointedstick** [comment] 2022-06-20 18:26
There are simply optional fields in an app's `.desktop` file that hint certain behaviors to desktop environments that implement special support for them. They are optional keys, which means there is 100% backwards compatibility for desktop environments that don't implement any special support for them.

I can tell you how the exact implementation of `SingleMainWindow=true` works for Plasma and GNOME Shell (I implemented it); both will hide the "open new window" context menu for the app if set. For desktop environments that don't implement any special handling for this key, nothing will change. 

For `PrefersNonDefaultGPU=true`, I'm not as familiar with the implementation, but again, these are hints for the desktop environment; no app-specific behavior is changed at all.

**Comment by probonopd** [comment] 2022-06-20 18:31
In the meantime of the meantime (until the above is implemented), one can do:

```
# Get appimagetool AppImage that contains outdated desktop-file-validate and extract it
wget https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage
chmod +x appimagetool-x86_64.AppImage
./appimagetool-x86_64.AppImage --appimage-extract

# Put newer desktop-file-validate inside
rm squashfs-root/usr/bin/desktop-file-validate
wget https://github.com/probonopd/static-tools/releases/download/continuous/desktop-file-validate-x86_64 -O squashfs-root/usr/bin/desktop-file-validate

# Repack AppImage
VERSION=1 ./appimagetool-x86_64.AppImage ./squashfs-root/usr/share/applications/appimagetool.desktop
```

**Comment by Pointedstick** [comment] 2022-06-20 18:35
Not sure what that means, can you clarify? Nothing is mandatory here; putting these keys in an app's .desktop file is one possible way to hint to the DE to handle the app in some specific way (e.g. hide the "open new window" action or always run it with a dedicated GPU), but there are theoretically different alternative ways to do it. It's just that those other ways weren't done, because we already have a cross-desktop method of communicating app-specific metadata around: .desktop files, and the XDG spec that underpins them.

**Comment by soredake** [comment] 2022-06-20 18:49
> For `PrefersNonDefaultGPU`, I'm not as familiar with the implementation, so imagine it probably hints to the window manager to run the app with a dedicated GPU (if present) when that key is set to true. But again, these are hints for the DE; no app-specific behavior is changed at all.

https://github.com/KDE/kio/blob/master/src/gui/kprocessrunner.cpp#L133
https://github.com/KDE/kinit/blob/master/src/klauncher/klauncher.cpp#L657

It just sets DRI_PRIME to 1

**Comment by Pointedstick** [comment] 2022-06-20 19:23
> > Not sure what that means, can you clarify?
> 
> From a shell script, how do I open an application with a dedicated GPU and make it hide the "open new window" entry?

In KDE-land, I would run `kstart5 <executable>` which will run the codepath that looks in the .desktop file for these keys and runs whatever logic handles their presence. I would assume GNOME has a similar thing. I'm not aware of a cross-desktop launcher thingy, though it may exist and I'm simply unaware of it.

As @soredake just pointed out, the implementation of how the DE handles these keys depends entirely on the DE. In Plasma's case, evidently all it does under the hood is set an environment variable. Presumably this environment variable gets set and used in GNOME Shell too. But again, it's DE-specific. The Desktop XDG spec simply governs a standardized way of communicating pieces of informationl it's entirely up to the DE how it wants to handle that information--if at all.

**Comment by TheAssassin** [comment] 2022-06-20 19:38
The discussion has moved away from the original topic quite a bit. Let's update desktop-file-utils and permit up-to-date desktop files in AppImages. There is no realistic chance to break compatibility with older systems anyway...

**Comment by Pointedstick** [comment] 2022-06-20 19:41
> Let's update desktop-file-utils and permit up-to-date desktop files in AppImages

Thanks, that sounds like a good solution.

> There is no realistic chance to break compatibility with older systems anyway...

As I understand it, there is in fact no chance at all; DEs on older systems ignore unknown keys in apps' desktop files. Ironically the only breakage is if you use an old `desktop-file-utils` version to validate data at build-time! :laughing:

**Comment by TheAssassin** [comment] 2022-06-20 19:43
> As I understand it, there is in fact no chance at all; DEs on older systems ignore unknown keys in apps' desktop files.

Yes, that's what I've been telling people in the past. I think all parsers are forward compatible (I further remember the spec implying this as well).

For the record, the proposal in https://github.com/AppImage/AppImageKit/issues/1171#issuecomment-1160733168 has two serious issues. First, we can just build desktop-file-utils ourselves in this process (dependencies on GitHub release provided files from random third party repositories are not a good idea, this is just too fragile). Second, I'd just make the entire validation a warning-level thing. appimagetool doesn't have to break when a validation fails. It can't be blamed if the contained desktop entry is broken. It's good to perform a validation, but technically there is no reason to prevent the AppImage from being built.

**Comment by Pointedstick** [comment] 2022-06-20 19:45
Yes, that seems sensible to me.

**Comment by probonopd** [comment] 2022-06-20 20:07
> appimagetool doesn't have to break when a validation fails.

That's a separate discussion to be had imho. I think broken AppImages should be prevented from being made.

For now, let's focus on getting a newer `desktop-file-validate` in. (Maybe even a patched one that just ignores unknown keys...)

**Comment by TheAssassin** [comment] 2022-06-20 20:11
Indeed that's for another issue.

**Comment by MCOfficer** [comment] 2022-06-20 20:12
Where would that discussion be had? I do not want to pollute this issue any further, but I have some opinions regarding the more abstract topic.

**Comment by TheAssassin** [comment] 2022-06-20 20:12
Create a new issue, please.

**Comment by txtsd** [comment] 2022-07-29 16:49
Thanks!

**Comment by TheAssassin** [comment] 2022-07-31 00:35
Still broken. And this is actually the fault of `desktop-file-utils`. Support for 1.5 has been merged just half a year ago apparently (https://github.com/freedesktop/xdg-desktop-file-utils/commit/56d220dd679c7c3a8f995a41a27a7d6f3df49dea), unfortunately the tool has not seen a new release in over two years. Seriously...

Even though it's a fair bit of work and not the best style, I'll update the bundled desktop-file-utils to that unreleased commit. I don't expect any issues.

**Comment by TheAssassin** [comment] 2022-08-01 00:19
Works now.

**Closed by TheAssassin** 2022-08-01 00:19 UTC
